# -*- coding: utf-8 -*-
"""day26_xgboost_credit_risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwMg5AxjLdHB8_C6p_VvjShEirR6nv8-
"""

# ============================================================
# DAY 26 — XGBOOST
# Credit Card Default Risk Prediction
# ============================================================

# Install first if needed:
# pip install pandas numpy matplotlib scikit-learn xgboost openpyxl

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    roc_curve
)

from xgboost import XGBClassifier


# ============================================================
# 1. CONFIGURATION
# ============================================================

RANDOM_STATE = 42

DATA_PATH = Path("default of credit card clients.xls")

print("=" * 70)
print("DAY 26 — XGBOOST")
print("Credit Card Default Risk Prediction")
print("=" * 70)


# ============================================================
# 2. LOAD DATASET
# ============================================================

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"\nDataset not found: {DATA_PATH}\n"
        "\nDownload the official UCI dataset and place the file "
        "in the same folder as this Python script."
    )

print("\nLoading dataset...")

df = pd.read_excel(DATA_PATH, header=1)

print("\nDataset loaded successfully!")
print("Shape:", df.shape)


# ============================================================
# 3. CLEAN COLUMN NAMES
# ============================================================

df.columns = [
    "ID",
    "LIMIT_BAL",
    "SEX",
    "EDUCATION",
    "MARRIAGE",
    "AGE",
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6",
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6",
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6",
    "DEFAULT"
]

print("\nColumns renamed successfully.")


# ============================================================
# 4. BASIC DATA UNDERSTANDING
# ============================================================

print("\n" + "=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

print("\nFirst 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())


# ============================================================
# 5. REMOVE DUPLICATES
# ============================================================

duplicate_count = df.duplicated().sum()

if duplicate_count > 0:
    df = df.drop_duplicates().copy()
    print(f"\nRemoved {duplicate_count} duplicate rows.")
else:
    print("\nNo duplicate rows found.")


# ============================================================
# 6. REMOVE ID
# ============================================================

# ID is only an identifier and should not be used as a predictive feature.

df = df.drop(columns=["ID"])

print("\nID column removed.")
print("Current shape:", df.shape)


# ============================================================
# 7. TARGET DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)

target_counts = df["DEFAULT"].value_counts().sort_index()

print(target_counts)

print("\nTarget percentages:")
print((df["DEFAULT"].value_counts(normalize=True) * 100).round(2))


# ============================================================
# 8. TARGET VISUALIZATION
# ============================================================

plt.figure(figsize=(6, 4))

plt.bar(
    ["No Default", "Default"],
    [
        target_counts.get(0, 0),
        target_counts.get(1, 0)
    ]
)

plt.title("Credit Card Default Distribution")
plt.xlabel("Default Status")
plt.ylabel("Number of Customers")

plt.tight_layout()
plt.show()


# ============================================================
# 9. FEATURE ENGINEERING
# ============================================================

print("\n" + "=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)

# ------------------------------------------------------------
# Credit utilization proxy
# ------------------------------------------------------------

df["AVG_BILL_AMT"] = df[
    [
        "BILL_AMT1",
        "BILL_AMT2",
        "BILL_AMT3",
        "BILL_AMT4",
        "BILL_AMT5",
        "BILL_AMT6"
    ]
].mean(axis=1)


# ------------------------------------------------------------
# Average payment amount
# ------------------------------------------------------------

df["AVG_PAY_AMT"] = df[
    [
        "PAY_AMT1",
        "PAY_AMT2",
        "PAY_AMT3",
        "PAY_AMT4",
        "PAY_AMT5",
        "PAY_AMT6"
    ]
].mean(axis=1)


# ------------------------------------------------------------
# Total payment amount
# ------------------------------------------------------------

df["TOTAL_PAY_AMT"] = df[
    [
        "PAY_AMT1",
        "PAY_AMT2",
        "PAY_AMT3",
        "PAY_AMT4",
        "PAY_AMT5",
        "PAY_AMT6"
    ]
].sum(axis=1)


# ------------------------------------------------------------
# Total bill amount
# ------------------------------------------------------------

df["TOTAL_BILL_AMT"] = df[
    [
        "BILL_AMT1",
        "BILL_AMT2",
        "BILL_AMT3",
        "BILL_AMT4",
        "BILL_AMT5",
        "BILL_AMT6"
    ]
].sum(axis=1)


# ------------------------------------------------------------
# Payment-to-bill ratio
# ------------------------------------------------------------

df["PAYMENT_BILL_RATIO"] = (
    df["AVG_PAY_AMT"] /
    (df["AVG_BILL_AMT"].abs() + 1)
)


# ------------------------------------------------------------
# Maximum repayment delay
# ------------------------------------------------------------

df["MAX_PAYMENT_DELAY"] = df[
    [
        "PAY_0",
        "PAY_2",
        "PAY_3",
        "PAY_4",
        "PAY_5",
        "PAY_6"
    ]
].max(axis=1)


# ------------------------------------------------------------
# Number of months with delayed payment
# ------------------------------------------------------------

payment_columns = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

df["DELAYED_MONTHS"] = (
    df[payment_columns] > 0
).sum(axis=1)


print("\nNew features created:")

new_features = [
    "AVG_BILL_AMT",
    "AVG_PAY_AMT",
    "TOTAL_PAY_AMT",
    "TOTAL_BILL_AMT",
    "PAYMENT_BILL_RATIO",
    "MAX_PAYMENT_DELAY",
    "DELAYED_MONTHS"
]

print(new_features)


# ============================================================
# 10. PREPARE X AND Y
# ============================================================

X = df.drop(columns=["DEFAULT"])
y = df["DEFAULT"]

print("\nFeature matrix shape:", X.shape)
print("Target shape:", y.shape)


# ============================================================
# 11. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y
)

print("\n" + "=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)

print("Training samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])


# ============================================================
# 12. CALCULATE CLASS IMBALANCE WEIGHT
# ============================================================

negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()

scale_pos_weight = negative_count / positive_count

print("\nNegative class:", negative_count)
print("Positive class:", positive_count)
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.2f}")


# ============================================================
# 13. LOGISTIC REGRESSION BASELINE
# ============================================================
print("LOGISTIC REGRESSION")
logistic_model = Pipeline(
    steps=[
        (
            "scaler",
            StandardScaler()
        ),
        (
            "model",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=RANDOM_STATE
            )
        )
    ]
)
logistic_model.fit(X_train, y_train)
logistic_pred = logistic_model.predict(X_test)
logistic_prob = logistic_model.predict_proba(X_test)[:, 1]
# ============================================================
# 14. RANDOM FOREST
# ============================================================
print("RANDOM FOREST")
random_forest = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=RANDOM_STATE,
    n_jobs=-1
)
random_forest.fit(X_train, y_train)
rf_pred = random_forest.predict(X_test)
rf_prob = random_forest.predict_proba(X_test)[:, 1]
# ============================================================
# 15. XGBOOST
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST")
print("=" * 70)

xgb_model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    min_child_weight=2,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0,
    reg_alpha=0.1,
    reg_lambda=1.0,
    scale_pos_weight=scale_pos_weight,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

print("\nTraining XGBoost...")

xgb_model.fit(
    X_train,
    y_train
)

xgb_pred = xgb_model.predict(X_test)

xgb_prob = xgb_model.predict_proba(X_test)[:, 1]

print("XGBoost training completed!")


# ============================================================
# 16. EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name, y_true, predictions, probabilities):

    return {
        "Model": model_name,
        "Accuracy": accuracy_score(
            y_true,
            predictions
        ),
        "Precision": precision_score(
            y_true,
            predictions,
            zero_division=0
        ),
        "Recall": recall_score(
            y_true,
            predictions,
            zero_division=0
        ),
        "F1 Score": f1_score(
            y_true,
            predictions,
            zero_division=0
        ),
        "ROC-AUC": roc_auc_score(
            y_true,
            probabilities
        )
    }


# ============================================================
# 17. MODEL COMPARISON
# ============================================================

results = []

results.append(
    evaluate_model(
        "Logistic Regression",
        y_test,
        logistic_pred,
        logistic_prob
    )
)

results.append(
    evaluate_model(
        "Random Forest",
        y_test,
        rf_pred,
        rf_prob
    )
)

results.append(
    evaluate_model(
        "XGBoost",
        y_test,
        xgb_pred,
        xgb_prob
    )
)

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="ROC-AUC",
    ascending=False
).reset_index(drop=True)


print("\n" + "=" * 70)
print("MODEL COMPARISON")
print("=" * 70)

print(
    results_df.round(4).to_string(index=False)
)


# ============================================================
# 18. MODEL COMPARISON VISUALIZATION
# ============================================================

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score",
    "ROC-AUC"
]

plot_df = results_df.set_index("Model")[metrics]

plot_df.plot(
    kind="bar",
    figsize=(8, 4)
)

plt.title("Credit Default Model Comparison")
plt.ylabel("Score")
plt.xlabel("Model")
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.legend(loc="lower right")

plt.tight_layout()
plt.show()


# ============================================================
# 19. SELECT BEST MODEL
# ============================================================

best_model_name = results_df.iloc[0]["Model"]

print("\n" + "=" * 70)
print("BEST MODEL")
print("=" * 70)

print(
    f"Best model based on ROC-AUC: {best_model_name}"
)

print(
    f"ROC-AUC: {results_df.iloc[0]['ROC-AUC']:.4f}"
)


# ============================================================
# 20. XGBOOST CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y_test,
        xgb_pred,
        target_names=[
            "No Default",
            "Default"
        ],
        zero_division=0
    )
)


# ============================================================
# 21. XGBOOST CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    xgb_pred
)

print("\nXGBoost Confusion Matrix:")
print(cm)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "No Default",
        "Default"
    ]
).plot()

plt.title("XGBoost Confusion Matrix")
plt.tight_layout()
plt.show()


# ============================================================
# 22. ROC CURVE COMPARISON
# ============================================================

plt.figure(figsize=(6, 4))

model_probabilities = {
    "Logistic Regression": logistic_prob,
    "Random Forest": rf_prob,
    "XGBoost": xgb_prob
}

for model_name, probabilities in model_probabilities.items():

    fpr, tpr, _ = roc_curve(
        y_test,
        probabilities
    )

    auc_score = roc_auc_score(
        y_test,
        probabilities
    )

    plt.plot(
        fpr,
        tpr,
        label=f"{model_name} (AUC={auc_score:.3f})"
    )


plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Random Classifier"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title(
    "ROC Curve — Credit Default Prediction"
)

plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# ============================================================
# 23. XGBOOST FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": xgb_model.feature_importances_
    }
)

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
).reset_index(drop=True)


print("\n" + "=" * 70)
print("TOP XGBOOST FEATURES")
print("=" * 70)

print(
    feature_importance.head(15).to_string(
        index=False
    )
)


# ============================================================
# 24. FEATURE IMPORTANCE VISUALIZATION
# ============================================================

top_features = (
    feature_importance
    .head(15)
    .sort_values("Importance")
)

plt.figure(figsize=(5, 5))

plt.barh(
    top_features["Feature"],
    top_features["Importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")

plt.title(
    "Top XGBoost Features"
)

plt.tight_layout()
plt.show()


# ============================================================
# 25. BUSINESS INSIGHTS
# ============================================================

default_rate = y.mean() * 100

print("\n" + "=" * 70)
print("BUSINESS INSIGHTS")
print("=" * 70)

print(
    f"\nOverall default rate: {default_rate:.2f}%"
)

print(
    "\nThe model can support credit-risk analysis by identifying "
    "customers with a higher predicted probability of default."
)

print(
    "\nImportant factors identified by XGBoost can help analysts "
    "understand which customer and repayment characteristics "
    "are associated with higher predicted risk."
)

print(
    "\nIn a real financial environment, model predictions should "
    "support human decision-making rather than automatically "
    "determining an individual's credit eligibility."
)


# ============================================================
# 26. SAVE RESULTS
# ============================================================

results_df.to_csv(
    "Day26_XGBoost_Model_Results.csv",
    index=False
)

feature_importance.to_csv(
    "Day26_XGBoost_Feature_Importance.csv",
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(
    "\n1. Day26_XGBoost_Model_Results.csv"
)

print(
    "2. Day26_XGBoost_Feature_Importance.csv"
)


# ============================================================
# 27. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DAY 26 COMPLETED 🚀")
print("=" * 70)

print(
    "\nProject: Credit Card Default Risk Prediction"
)

print(
    "Main Algorithm: XGBoost"
)

print(
    f"Best Model by ROC-AUC: {best_model_name}"
)

print(
    "\nConcepts covered:"
)

print(
    "✓ XGBoost"
)

print(
    "✓ Gradient Boosting"
)

print(
    "✓ Class Imbalance"
)

print(
    "✓ Feature Engineering"
)

print(
    "✓ Model Comparison"
)

print(
    "✓ ROC-AUC"
)

print(
    "✓ Confusion Matrix"
)

print(
    "✓ Feature Importance"
)

print(
    "✓ Business Interpretation"
)

print(
    "\nDay 26/30 — XGBoost completed! ⚡"
)