# -*- coding: utf-8 -*-
"""Day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFn7UFFNaHViL7EdOosvrbLkrFAI6vtf
"""

"""
Day 6 - Machine Learning Workflow & Train-Test Split
30 Days of Machine Learning Challenge
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split


# ==========================================
# 1. Create Dataset
# ==========================================

data = {
    "Study_Hours": [1, 2, 2.5, 3, 3.5, 4, 5, 5.5, 6, 7],
    "Marks": [35, 42, 48, 55, 60, 65, 72, 78, 85, 92]
}

df = pd.DataFrame(data)

print("Dataset:")
print(df)


# ==========================================
# 2. Explore Dataset
# ==========================================

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nInformation:")
df.info()

print("\nStatistical Summary:")
print(df.describe())


# ==========================================
# 3. Visualization
# ==========================================

plt.figure(figsize=(6, 3))

plt.scatter(
    df["Study_Hours"],
    df["Marks"]
)

plt.title("Study Hours vs Marks")
plt.xlabel("Study Hours")
plt.ylabel("Marks")

plt.show()


# ==========================================
# 4. Features and Target
# ==========================================

X = df[["Study_Hours"]]

y = df["Marks"]

print("\nFeatures:")
print(X)

print("\nTarget:")
print(y)


# ==========================================
# 5. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# ==========================================
# 6. Display Split Data
# ==========================================

print("\nTraining Features:")
print(X_train)

print("\nTesting Features:")
print(X_test)

print("\nTraining Target:")
print(y_train)

print("\nTesting Target:")
print(y_test)


# ==========================================
# 7. Dataset Sizes
# ==========================================

print("\nTotal Records:", len(df))
print("Training Records:", len(X_train))
print("Testing Records:", len(X_test))


# ==========================================
# 8. Final Summary
# ==========================================

print("\nMachine Learning Workflow:")
print("1. Data Collection")
print("2. Data Exploration")
print("3. Data Preprocessing")
print("4. Feature and Target Selection")
print("5. Train-Test Split")
print("6. Model Training")
print("7. Prediction")
print("8. Evaluation")

"""
Day 6 - Machine Learning Workflow & Train-Test Split
30 Days of Machine Learning Challenge
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split


# ==========================================
# 1. Load Dataset
# ==========================================

df = pd.read_csv("StudentPerformanceFactors.csv")

print("First 5 Records:")
print(df.head())


# ==========================================
# 2. Explore Dataset
# ==========================================

print("\nDataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())


# ==========================================
# 3. Missing Values
# ==========================================

print("\nMissing Values:")
print(df.isnull().sum())


# ==========================================
# 4. Duplicate Records
# ==========================================

print("\nDuplicate Records:")
print(df.duplicated().sum())


# ==========================================
# 5. Select Features and Target
# ==========================================

features = [
    "Hours_Studied",
    "Attendance",
    "Previous_Scores",
    "Sleep_Hours",
    "Tutoring_Sessions"
]

X = df[features]

y = df["Exam_Score"]

print("\nSelected Features:")
print(X.head())

print("\nTarget:")
print(y.head())


# ==========================================
# 6. Feature Statistics
# ==========================================

print("\nFeature Statistics:")
print(X.describe())


# ==========================================
# 7. Visualization
# ==========================================

plt.figure(figsize=(8, 5))

plt.scatter(
    df["Hours_Studied"],
    df["Exam_Score"]
)

plt.title("Hours Studied vs Exam Score")
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")

plt.tight_layout()
plt.show()


# ==========================================
# 8. Attendance vs Exam Score
# ==========================================

plt.figure(figsize=(8, 5))

plt.scatter(
    df["Attendance"],
    df["Exam_Score"]
)

plt.title("Attendance vs Exam Score")
plt.xlabel("Attendance")
plt.ylabel("Exam Score")

plt.tight_layout()
plt.show()


# ==========================================
# 9. Correlation
# ==========================================

correlation = df[
    features + ["Exam_Score"]
].corr()

print("\nCorrelation Matrix:")
print(correlation)


# ==========================================
# 10. Correlation Heatmap
# ==========================================

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f"
)

plt.title("Feature Correlation with Exam Score")

plt.tight_layout()
plt.show()


# ==========================================
# 11. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# ==========================================
# 12. Dataset Split
# ==========================================

print("\nDataset Split")
print("----------------------")

print("Total Records:", len(df))
print("Training Records:", len(X_train))
print("Testing Records:", len(X_test))


# ==========================================
# 13. Training Data
# ==========================================

print("\nTraining Features:")
print(X_train.head())

print("\nTraining Target:")
print(y_train.head())


# ==========================================
# 14. Testing Data
# ==========================================

print("\nTesting Features:")
print(X_test.head())

print("\nTesting Target:")
print(y_test.head())