# -*- coding: utf-8 -*-
"""day20_hierarchical_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dP1iV99Qum0r6L_SdG_qZAWYpRzIxsAX
"""

# ============================================================
# DAY 20 - HIERARCHICAL CLUSTERING
# Dataset: Mall Customers
# Technique: Agglomerative Hierarchical Clustering
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage


# ============================================================
# 1. PROJECT INTRODUCTION
# ============================================================

print("=" * 65)
print("DAY 20 - HIERARCHICAL CLUSTERING")
print("=" * 65)

print("""
Hierarchical Clustering is an unsupervised learning technique
used to group similar observations into clusters.

In this project, customers are segmented using:
- Annual Income
- Spending Score
""")


# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv("Mall_Customers.csv")

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 3. CHECK DATASET COLUMNS
# ============================================================

print("\n" + "=" * 65)
print("DATASET COLUMNS")
print("=" * 65)

print(df.columns.tolist())


# ============================================================
# 4. DATA EXPLORATION
# ============================================================

print("\n" + "=" * 65)
print("DATASET INFORMATION")
print("=" * 65)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Information:")
df.info()


# ============================================================
# 5. FEATURE SELECTION
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SELECTION")
print("=" * 65)

# Features used for customer segmentation
features = [
    "Annual Income (k$)",
    "Spending Score (1-100)"
]

# Check whether required columns exist
missing_columns = [
    column for column in features
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Required columns are missing: {missing_columns}"
    )

X = df[features]

print("\nFeatures Used:")
print(features)

print("\nFirst 5 Feature Rows:")
print(X.head())


# ============================================================
# 6. VISUALIZE ORIGINAL DATA
# ============================================================

plt.figure(figsize=(6, 4))

plt.scatter(
    X["Annual Income (k$)"],
    X["Spending Score (1-100)"],
    alpha=0.7
)

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title("Customer Data Before Clustering")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# 7. FEATURE SCALING
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SCALING")
print("=" * 65)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Features standardized successfully.")

print("\nFirst 5 Scaled Rows:")
print(X_scaled[:5])


# ============================================================
# 8. CREATE LINKAGE MATRIX
# ============================================================

print("\n" + "=" * 65)
print("HIERARCHICAL CLUSTERING")
print("=" * 65)

print("""
Linkage Method : Ward
Distance        : Euclidean
""")

linked = linkage(
    X_scaled,
    method="ward"
)

print("Linkage matrix created successfully.")

print("\nFirst 5 rows of linkage matrix:")
print(linked[:5])


# ============================================================
# 9. DENDROGRAM
# ============================================================

print("\nGenerating dendrogram...")

plt.figure(figsize=(6, 4))

dendrogram(
    linked,
    truncate_mode="lastp",
    p=30,
    leaf_rotation=90,
    leaf_font_size=9
)

plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Cluster / Data Points")
plt.ylabel("Distance")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# 10. APPLY AGGLOMERATIVE CLUSTERING
# ============================================================

print("\n" + "=" * 65)
print("AGGLOMERATIVE CLUSTERING")
print("=" * 65)

# Number of clusters selected from the
# structure observed in the dendrogram.
n_clusters = 5

model = AgglomerativeClustering(
    n_clusters=n_clusters,
    linkage="ward"
)

cluster_labels = model.fit_predict(X_scaled)

print(
    f"Number of Clusters: {n_clusters}"
)

print("Clustering completed successfully.")


# ============================================================
# 11. ADD CLUSTER LABELS
# ============================================================

df["Cluster"] = cluster_labels

print("\n" + "=" * 65)
print("CUSTOMER DATA WITH CLUSTER LABELS")
print("=" * 65)

# Only use columns that are actually present
display_columns = [
    "CustomerID",
    "Age",
    "Annual Income (k$)",
    "Spending Score (1-100)",
    "Cluster"
]

# Keep only existing columns
display_columns = [
    column for column in display_columns
    if column in df.columns
]

print(
    df[display_columns].head(15)
)


# ============================================================
# 12. CLUSTER COUNTS
# ============================================================

print("\n" + "=" * 65)
print("CUSTOMERS IN EACH CLUSTER")
print("=" * 65)

cluster_counts = (
    df["Cluster"]
    .value_counts()
    .sort_index()
)

print(cluster_counts)


# ============================================================
# 13. CLUSTER VISUALIZATION
# ============================================================

plt.figure(figsize=(6, 5))

for cluster in sorted(df["Cluster"].unique()):

    cluster_data = df[
        df["Cluster"] == cluster
    ]

    plt.scatter(
        cluster_data["Annual Income (k$)"],
        cluster_data["Spending Score (1-100)"],
        label=f"Cluster {cluster}",
        alpha=0.7
    )

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title(
    "Hierarchical Clustering - Customer Segmentation"
)

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()


# ============================================================
# 14. CLUSTER SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("CLUSTER SUMMARY")
print("=" * 65)

cluster_summary = (
    df.groupby("Cluster")
    [
        [
            "Age",
            "Annual Income (k$)",
            "Spending Score (1-100)"
        ]
    ]
    .mean()
    .round(2)
)

print(cluster_summary)


# ============================================================
# 15. CLUSTER SIZE
# ============================================================

print("\n" + "=" * 65)
print("CLUSTER SIZE")
print("=" * 65)

cluster_size = (
    df.groupby("Cluster")
    .size()
    .reset_index(name="Customer Count")
)

print(cluster_size)


# ============================================================
# 16. CUSTOMER SEGMENT INTERPRETATION
# ============================================================

print("\n" + "=" * 65)
print("CUSTOMER SEGMENT INTERPRETATION")
print("=" * 65)

print("""
Use the cluster averages above to understand
the characteristics of each customer segment.

For example:

High Income + High Spending
    -> Potential high-value customers

High Income + Low Spending
    -> Potential growth opportunity

Low Income + High Spending
    -> Strong spending behavior

Low Income + Low Spending
    -> Lower-spending segment
""")


# ============================================================
# 17. HIERARCHICAL CLUSTERING VS K-MEANS
# ============================================================

print("\n" + "=" * 65)
print("HIERARCHICAL CLUSTERING vs K-MEANS")
print("=" * 65)

comparison = pd.DataFrame({
    "K-Means": [
        "Centroid-based",
        "Requires K",
        "Iterative",
        "Uses centroids"
    ],
    "Hierarchical": [
        "Hierarchy-based",
        "Can inspect dendrogram",
        "Builds hierarchy",
        "Uses cluster merging"
    ]
})

comparison.index = [
    "Approach",
    "Number of Clusters",
    "Process",
    "Main Concept"
]

print(comparison)


# ============================================================
# 18. SAVE CLUSTERED DATASET
# ============================================================

output_file = (
    "Mall_Customers_Hierarchical_Clustered.csv"
)

df.to_csv(
    output_file,
    index=False
)

print(
    f"\nClustered dataset saved as: {output_file}"
)


# ============================================================
# 19. FINAL RESULTS
# ============================================================

print("\n" + "=" * 65)
print("DAY 20 - FINAL RESULTS")
print("=" * 65)

print(
    f"Total Customers    : {len(df)}"
)

print(
    f"Features Used      : {X.shape[1]}"
)

print(
    f"Number of Clusters : {n_clusters}"
)

print("\nCluster Sizes:")
print(cluster_counts)

print("\nCluster Summary:")
print(cluster_summary)

print("\nOutput File:")
print(output_file)

print("\nDay 20 Hierarchical Clustering Complete! 🚀")

print("=" * 65)