# -*- coding: utf-8 -*-
"""day19_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DR4T80Q9GdPqwQCsz-Y2F3ZzmtyIBZmJ
"""

# ============================================================
# DAY 19 - K-MEANS CLUSTERING
# Dataset: Mall Customers
# Technique: Unsupervised Learning
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


# ============================================================
# 1. PROJECT INTRODUCTION
# ============================================================

print("=" * 65)
print("DAY 19 - K-MEANS CLUSTERING")
print("=" * 65)

print("""
K-Means is an unsupervised learning algorithm used to
group similar data points into clusters.

In this project, customer data is grouped based on
Annual Income and Spending Score.
""")


# ============================================================
# 2. LOAD DATASET
# ============================================================

# Kaggle Mall Customers dataset
# Expected file name:
# Mall_Customers.csv

df = pd.read_csv("Mall_Customers.csv")

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 3. DATA INFORMATION
# ============================================================

print("\n" + "=" * 65)
print("DATASET INFORMATION")
print("=" * 65)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Information:")
df.info()


# ============================================================
# 4. SELECT FEATURES
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SELECTION")
print("=" * 65)

# Use Annual Income and Spending Score
X = df[
    [
        "Annual Income (k$)",
        "Spending Score (1-100)"
    ]
]

print("\nFeatures Used:")
print(X.columns.tolist())

print("\nFirst 5 Feature Rows:")
print(X.head())


# ============================================================
# 5. VISUALIZE ORIGINAL DATA
# ============================================================

plt.figure(figsize=(6, 4))

plt.scatter(
    X["Annual Income (k$)"],
    X["Spending Score (1-100)"],
    alpha=0.7
)

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title("Customer Data Before Clustering")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# 6. FEATURE SCALING
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SCALING")
print("=" * 65)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Features standardized successfully.")

print("\nFirst 5 Scaled Rows:")
print(X_scaled[:5])


# ============================================================
# 7. ELBOW METHOD
# ============================================================

print("\n" + "=" * 65)
print("ELBOW METHOD")
print("=" * 65)

inertia = []

K_values = range(1, 11)

for k in K_values:

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    model.fit(X_scaled)

    inertia.append(
        model.inertia_
    )

print("\nInertia Values:")

for k, value in zip(
    K_values,
    inertia
):

    print(
        f"K = {k} → Inertia = {value:.2f}"
    )


# ============================================================
# 8. ELBOW PLOT
# ============================================================

plt.figure(figsize=(6, 3))

plt.plot(
    K_values,
    inertia,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia / WCSS")
plt.title("Elbow Method for Optimal K")

plt.xticks(
    list(K_values)
)

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# 9. APPLY K-MEANS
# ============================================================

print("\n" + "=" * 65)
print("K-MEANS CLUSTERING")
print("=" * 65)

# Based on the typical elbow pattern in this dataset,
# K = 5 is used.

optimal_k = 5

kmeans = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=10
)

cluster_labels = kmeans.fit_predict(
    X_scaled
)

print(
    f"Number of Clusters: {optimal_k}"
)


# ============================================================
# 10. ADD CLUSTER LABELS
# ============================================================

df["Cluster"] = cluster_labels

print("\nCustomer Data with Cluster Labels:")

print(
    df[
        [
            "CustomerID",
            "Annual Income (k$)",
            "Spending Score (1-100)",
            "Cluster"
        ]
    ].head(15)
)


# ============================================================
# 11. CLUSTER COUNTS
# ============================================================

print("\n" + "=" * 65)
print("CUSTOMERS IN EACH CLUSTER")
print("=" * 65)

cluster_counts = (
    df["Cluster"]
    .value_counts()
    .sort_index()
)

print(cluster_counts)


# ============================================================
# 12. CLUSTER VISUALIZATION
# ============================================================

plt.figure(figsize=(6, 4))

for cluster in sorted(
    df["Cluster"].unique()
):

    cluster_data = df[
        df["Cluster"] == cluster
    ]

    plt.scatter(
        cluster_data["Annual Income (k$)"],
        cluster_data["Spending Score (1-100)"],
        label=f"Cluster {cluster}",
        alpha=0.7
    )


# Convert cluster centers back to original scale
centers_original = scaler.inverse_transform(
    kmeans.cluster_centers_
)

plt.scatter(
    centers_original[:, 0],
    centers_original[:, 1],
    marker="X",
    s=200,
    label="Centroids"
)

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title("K-Means Customer Segmentation")

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()


# ============================================================
# 13. CLUSTER SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("CLUSTER SUMMARY")
print("=" * 65)

cluster_summary = (
    df.groupby("Cluster")
    [
        [
            "Age",
            "Annual Income (k$)",
            "Spending Score (1-100)"
        ]
    ]
    .mean()
    .round(2)
)

print(cluster_summary)


# ============================================================
# 14. CLUSTER SIZE
# ============================================================

cluster_size = (
    df.groupby("Cluster")
    .size()
    .reset_index(name="Customer Count")
)

print("\nCluster Size:")
print(cluster_size)


# ============================================================
# 15. CLUSTER CENTROIDS
# ============================================================

print("\n" + "=" * 65)
print("CLUSTER CENTROIDS")
print("=" * 65)

centroids = pd.DataFrame(
    centers_original,
    columns=[
        "Annual Income (k$)",
        "Spending Score (1-100)"
    ]
)

centroids.index.name = "Cluster"

print(
    centroids.round(2)
)


# ============================================================
# 16. PCA VISUALIZATION
# ============================================================

print("\n" + "=" * 65)
print("PCA VISUALIZATION")
print("=" * 65)

# PCA is used only to demonstrate dimensionality
# reduction for visualization.

pca = PCA(
    n_components=2
)

X_pca = pca.fit_transform(
    X_scaled
)

print(
    "Original Dimensions:",
    X_scaled.shape[1]
)

print(
    "PCA Dimensions:",
    X_pca.shape[1]
)

print(
    "Variance Explained:",
    pca.explained_variance_ratio_.sum()
)


# ============================================================
# 17. PCA CLUSTER PLOT
# ============================================================

plt.figure(figsize=(6, 4))

for cluster in sorted(
    df["Cluster"].unique()
):

    mask = (
        df["Cluster"] == cluster
    )

    plt.scatter(
        X_pca[mask, 0],
        X_pca[mask, 1],
        label=f"Cluster {cluster}",
        alpha=0.7
    )

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.title(
    "K-Means Clusters Visualized Using PCA"
)

plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()


# ============================================================
# 18. SAVE CLUSTERED DATA
# ============================================================

output_file = (
    "Mall_Customers_Clustered.csv"
)

df.to_csv(
    output_file,
    index=False
)

print(
    f"\nClustered dataset saved as: "
    f"{output_file}"
)


# ============================================================
# 19. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("DAY 19 - FINAL SUMMARY")
print("=" * 65)

print(
    f"Original Customers : {len(df)}"
)

print(
    f"Features Used      : {X.shape[1]}"
)

print(
    f"Number of Clusters : {optimal_k}"
)

print(
    f"Final Inertia      : "
    f"{kmeans.inertia_:.2f}"
)

print(
    f"PCA Variance       : "
    f"{pca.explained_variance_ratio_.sum():.4f}"
)

print("\nCluster Sizes:")

print(cluster_counts)

print(
    "\nDay 19 K-Means Clustering Complete! 🚀"
)

print("=" * 65)