# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9QmqJffwq3zXeaGR1RNhxcTRVCwWU1Q
"""

"""
Day 4 - Pandas for Machine Learning
30 Days of Machine Learning Challenge
"""

import pandas as pd


# ==========================================
# 1. Pandas Version
# ==========================================

print("Pandas Version:", pd.__version__)


# ==========================================
# 2. Create Series
# ==========================================

marks = pd.Series([70, 80, 90, 85, 95])

print("\nSeries:")
print(marks)


# ==========================================
# 3. Create DataFrame
# ==========================================

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Neha"],
    "Age": [22, 21, 23, 22, 24],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai"],
    "Marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)

print("\nDataFrame:")
print(df)


# ==========================================
# 4. Explore Dataset
# ==========================================

print("\nFirst 5 Records:")
print(df.head())

print("\nLast 5 Records:")
print(df.tail())

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())


# ==========================================
# 5. Select Columns
# ==========================================

print("\nMarks Column:")
print(df["Marks"])

print("\nName and Marks:")
print(df[["Name", "Marks"]])


# ==========================================
# 6. Select Rows
# ==========================================

print("\nFirst Row:")
print(df.iloc[0])

print("\nFirst Three Rows:")
print(df.iloc[0:3])


# ==========================================
# 7. Filtering
# ==========================================

print("\nStudents with Marks > 80:")
print(df[df["Marks"] > 80])

print("\nStudents from Pune:")
print(df[df["City"] == "Pune"])


# ==========================================
# 8. Sorting
# ==========================================

print("\nSorted by Marks:")
print(df.sort_values("Marks", ascending=False))


# ==========================================
# 9. Missing Values
# ==========================================

df_missing = df.copy()

df_missing.loc[2, "Marks"] = None

print("\nMissing Values:")
print(df_missing.isnull().sum())

df_missing["Marks"] = df_missing["Marks"].fillna(
    df_missing["Marks"].mean()
)

print("\nAfter Filling Missing Values:")
print(df_missing)


# ==========================================
# 10. GroupBy
# ==========================================

print("\nAverage Marks by City:")
print(df.groupby("City")["Marks"].mean())


# ==========================================
# 11. Basic Statistics
# ==========================================

print("\nAverage Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())


# ==========================================
# 12. Create New Column
# ==========================================

df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

print("\nFinal Dataset:")
print(df)


print("\n🎉 Day 4 Completed!")