# -*- coding: utf-8 -*-
"""day21_dbscan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIL14mbS84C66n93EnWQ2VotiAP1zr-d
"""

# ============================================================
# DAY 21 - DBSCAN CLUSTERING
# Dataset: Mall Customers
# Technique: Density-Based Spatial Clustering
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN


# ============================================================
# 1. PROJECT INTRODUCTION
# ============================================================

print("=" * 65)
print("DAY 21 - DBSCAN CLUSTERING")
print("=" * 65)

print("""
DBSCAN (Density-Based Spatial Clustering of Applications
with Noise) is an unsupervised learning algorithm that
groups data points based on density.

Unlike K-Means, DBSCAN:
- Does not require the number of clusters beforehand
- Can detect noise and outliers
- Can identify clusters with irregular shapes
""")


# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv("Mall_Customers.csv")

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 3. DATA EXPLORATION
# ============================================================

print("\n" + "=" * 65)
print("DATASET INFORMATION")
print("=" * 65)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())


# ============================================================
# 4. FEATURE SELECTION
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SELECTION")
print("=" * 65)

features = [
    "Annual Income (k$)",
    "Spending Score (1-100)"
]

# Check required columns
missing_columns = [
    column for column in features
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Required columns are missing: {missing_columns}"
    )

X = df[features]

print("\nFeatures Used:")
print(features)

print("\nFirst 5 Rows:")
print(X.head())


# ============================================================
# 5. VISUALIZE ORIGINAL DATA
# ============================================================

plt.figure(figsize=(9, 6))

plt.scatter(
    X["Annual Income (k$)"],
    X["Spending Score (1-100)"],
    alpha=0.7
)

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title("Customer Data Before DBSCAN")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ============================================================
# 6. FEATURE SCALING
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SCALING")
print("=" * 65)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Features standardized successfully.")

print("\nFirst 5 Scaled Rows:")
print(X_scaled[:5])


# ============================================================
# 7. APPLY DBSCAN
# ============================================================

print("\n" + "=" * 65)
print("APPLYING DBSCAN")
print("=" * 65)

# eps:
# Maximum distance between two samples for them
# to be considered neighbors.

# min_samples:
# Minimum number of samples required to form
# a dense region.

eps_value = 0.35
min_samples_value = 5

dbscan = DBSCAN(
    eps=eps_value,
    min_samples=min_samples_value
)

cluster_labels = dbscan.fit_predict(X_scaled)

print(f"eps         : {eps_value}")
print(f"min_samples : {min_samples_value}")

print("\nDBSCAN clustering completed.")


# ============================================================
# 8. ADD CLUSTER LABELS
# ============================================================

df["Cluster"] = cluster_labels

print("\n" + "=" * 65)
print("CUSTOMER DATA WITH CLUSTER LABELS")
print("=" * 65)

display_columns = [
    "CustomerID",
    "Age",
    "Annual Income (k$)",
    "Spending Score (1-100)",
    "Cluster"
]

# Keep only columns available in the dataset
display_columns = [
    column for column in display_columns
    if column in df.columns
]

print(
    df[display_columns].head(15)
)


# ============================================================
# 9. IDENTIFY NUMBER OF CLUSTERS
# ============================================================

unique_labels = set(cluster_labels)

# DBSCAN uses -1 for noise/outliers
cluster_labels_without_noise = [
    label for label in unique_labels
    if label != -1
]

number_of_clusters = len(
    cluster_labels_without_noise
)

print("\n" + "=" * 65)
print("DBSCAN RESULTS")
print("=" * 65)

print(
    "Number of Clusters:",
    number_of_clusters
)


# ============================================================
# 10. COUNT NOISE POINTS
# ============================================================

noise_count = list(
    cluster_labels
).count(-1)

print(
    "Number of Noise Points:",
    noise_count
)


# ============================================================
# 11. CLUSTER COUNTS
# ============================================================

print("\n" + "=" * 65)
print("CUSTOMERS IN EACH CLUSTER")
print("=" * 65)

cluster_counts = (
    df["Cluster"]
    .value_counts()
    .sort_index()
)

print(cluster_counts)


# ============================================================
# 12. VISUALIZE DBSCAN CLUSTERS
# ============================================================

plt.figure(figsize=(7, 5))

for cluster in sorted(
    df["Cluster"].unique()
):

    cluster_data = df[
        df["Cluster"] == cluster
    ]

    if cluster == -1:

        plt.scatter(
            cluster_data["Annual Income (k$)"],
            cluster_data["Spending Score (1-100)"],
            label="Noise / Outliers",
            marker="x",
            s=80
        )

    else:

        plt.scatter(
            cluster_data["Annual Income (k$)"],
            cluster_data["Spending Score (1-100)"],
            label=f"Cluster {cluster}",
            alpha=0.7
        )


plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")

plt.title(
    "DBSCAN Customer Segmentation"
)

plt.legend()

plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()


# ============================================================
# 13. CLUSTER SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("CLUSTER SUMMARY")
print("=" * 65)

# Exclude noise (-1) from average cluster analysis
clustered_customers = df[
    df["Cluster"] != -1
]

if not clustered_customers.empty:

    cluster_summary = (
        clustered_customers
        .groupby("Cluster")
        [
            [
                "Age",
                "Annual Income (k$)",
                "Spending Score (1-100)"
            ]
        ]
        .mean()
        .round(2)
    )

    print(cluster_summary)

else:

    print(
        "No clusters were detected with the current parameters."
    )


# ============================================================
# 14. NOISE / OUTLIER ANALYSIS
# ============================================================

print("\n" + "=" * 65)
print("NOISE / OUTLIER ANALYSIS")
print("=" * 65)

if noise_count > 0:

    noise_points = df[
        df["Cluster"] == -1
    ]

    print(
        f"DBSCAN identified {noise_count} "
        "potential noise/outlier points."
    )

    print("\nNoise Points:")
    print(
        noise_points[display_columns]
    )

else:

    print(
        "No noise points were detected "
        "with the current DBSCAN parameters."
    )


# ============================================================
# 15. DBSCAN PARAMETERS
# ============================================================

print("\n" + "=" * 65)
print("DBSCAN PARAMETERS")
print("=" * 65)

print(f"""
eps = {eps_value}

Controls the maximum neighborhood distance.

min_samples = {min_samples_value}

Controls the minimum number of points required
to form a dense region.
""")


# ============================================================
# 16. DBSCAN vs K-MEANS
# ============================================================

print("\n" + "=" * 65)
print("DBSCAN vs K-MEANS")
print("=" * 65)

comparison = pd.DataFrame({
    "K-Means": [
        "Requires K",
        "Centroid-based",
        "Sensitive to outliers",
        "Works well with compact clusters"
    ],

    "DBSCAN": [
        "Does not require K",
        "Density-based",
        "Can identify noise",
        "Can identify irregular clusters"
    ]
})

comparison.index = [
    "Number of Clusters",
    "Approach",
    "Outliers",
    "Cluster Shape"
]

print(comparison)


# ============================================================
# 17. SAVE CLUSTERED DATASET
# ============================================================

output_file = (
    "Mall_Customers_DBSCAN_Clustered.csv"
)

df.to_csv(
    output_file,
    index=False
)

print(
    f"\nClustered dataset saved as: "
    f"{output_file}"
)


# ============================================================
# 18. FINAL RESULTS
# ============================================================

print("\n" + "=" * 65)
print("DAY 21 - FINAL RESULTS")
print("=" * 65)

print(
    f"Total Customers       : {len(df)}"
)

print(
    f"Features Used         : {X.shape[1]}"
)

print(
    f"Clusters Detected     : {number_of_clusters}"
)

print(
    f"Noise / Outliers      : {noise_count}"
)

print(
    f"eps                   : {eps_value}"
)

print(
    f"min_samples           : {min_samples_value}"
)

print(
    f"Output File           : {output_file}"
)

print(
    "\nDay 21 DBSCAN Clustering Complete! 🚀"
)

print("=" * 65)