# -*- coding: utf-8 -*-
"""day27_End_to_End_ML_Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2aXstS5AHHAJTodEp_VoCbXjgu4SxVI
"""

# ============================================================
# DAY 27 — END-TO-END MACHINE LEARNING PIPELINE
# Project: Wine Classification
# Dataset: Built-in Scikit-learn Wine Dataset
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. CONFIGURATION
# ============================================================

MODEL_FILE = "day27_wine_classification_pipeline.pkl"
RESULTS_FILE = "Day27_Model_Results.csv"


# ============================================================
# 2. LOAD BUILT-IN DATASET
# ============================================================

print("\n" + "=" * 65)
print("DAY 27 — END-TO-END MACHINE LEARNING PIPELINE")
print("=" * 65)

print("\n[1] Loading Scikit-learn Wine Dataset...")

wine = load_wine()

X = pd.DataFrame(
    wine.data,
    columns=wine.feature_names
)

y = pd.Series(
    wine.target,
    name="target"
)

print("\nDataset loaded successfully!")

print("Number of samples :", X.shape[0])
print("Number of features:", X.shape[1])
print("Number of classes :", len(wine.target_names))


# ============================================================
# 3. DATA UNDERSTANDING
# ============================================================

print("\n" + "-" * 65)
print("[2] DATA UNDERSTANDING")
print("-" * 65)

print("\nFirst 5 rows:")
print(X.head())

print("\nFeature names:")
print(X.columns.tolist())

print("\nTarget classes:")
for index, name in enumerate(wine.target_names):
    print(f"{index} → {name}")

print("\nDataset shape:")
print(X.shape)

print("\nMissing values:")
print(X.isnull().sum().sum())

print("\nTarget distribution:")
print(y.value_counts().sort_index())


# ============================================================
# 4. BASIC DATA ANALYSIS
# ============================================================

print("\n" + "-" * 65)
print("[3] BASIC DATA ANALYSIS")
print("-" * 65)

print("\nStatistical summary:")
print(X.describe())


# ============================================================
# 5. TARGET DISTRIBUTION
# ============================================================

plt.figure(figsize=(7, 5))

y.value_counts().sort_index().plot(
    kind="bar"
)

plt.title("Wine Dataset — Class Distribution")
plt.xlabel("Wine Class")
plt.ylabel("Number of Samples")
plt.xticks(
    ticks=range(len(wine.target_names)),
    labels=wine.target_names,
    rotation=0
)

plt.tight_layout()
plt.show()


# ============================================================
# 6. TRAIN-TEST SPLIT
# ============================================================

print("\n" + "-" * 65)
print("[4] TRAIN-TEST SPLIT")
print("-" * 65)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])


# ============================================================
# 7. BUILD PREPROCESSING PIPELINE
# ============================================================

print("\n" + "-" * 65)
print("[5] BUILDING PREPROCESSING PIPELINE")
print("-" * 65)

preprocessing = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)


# ============================================================
# 8. MACHINE LEARNING MODEL
# ============================================================

print("\n[6] Creating Logistic Regression Model...")

model = LogisticRegression(
    max_iter=2000,
    random_state=42
)


# ============================================================
# 9. COMPLETE END-TO-END PIPELINE
# ============================================================

ml_pipeline = Pipeline(
    steps=[
        (
            "preprocessing",
            preprocessing
        ),
        (
            "model",
            model
        )
    ]
)

print("\nComplete Pipeline:")
print(ml_pipeline)


# ============================================================
# 10. TRAIN PIPELINE
# ============================================================

print("\n" + "-" * 65)
print("[7] TRAINING MODEL")
print("-" * 65)

ml_pipeline.fit(
    X_train,
    y_train
)

print("\nModel trained successfully! ✅")


# ============================================================
# 11. MAKE PREDICTIONS
# ============================================================

print("\n" + "-" * 65)
print("[8] MAKING PREDICTIONS")
print("-" * 65)

y_pred = ml_pipeline.predict(X_test)

print("\nPredictions generated successfully! ✅")


# ============================================================
# 12. MODEL EVALUATION
# ============================================================

print("\n" + "-" * 65)
print("[9] MODEL EVALUATION")
print("-" * 65)

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted",
    zero_division=0
)


print(f"\nAccuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")


# ============================================================
# 13. CLASSIFICATION REPORT
# ============================================================

print("\n" + "-" * 65)
print("[10] CLASSIFICATION REPORT")
print("-" * 65)

print(
    classification_report(
        y_test,
        y_pred,
        target_names=wine.target_names,
        zero_division=0
    )
)


# ============================================================
# 14. CONFUSION MATRIX
# ============================================================

print("\n" + "-" * 65)
print("[11] CONFUSION MATRIX")
print("-" * 65)

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=wine.target_names
)

disp.plot()

plt.title("Day 27 — Wine Classification Confusion Matrix")
plt.tight_layout()
plt.show()


# ============================================================
# 15. SAVE MODEL RESULTS
# ============================================================

results = pd.DataFrame(
    {
        "Metric": [
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score"
        ],
        "Score": [
            accuracy,
            precision,
            recall,
            f1
        ]
    }
)

results.to_csv(
    RESULTS_FILE,
    index=False
)

print(
    f"\nModel results saved to: {RESULTS_FILE}"
)


# ============================================================
# 16. SAVE COMPLETE PIPELINE
# ============================================================

print("\n" + "-" * 65)
print("[12] SAVING COMPLETE PIPELINE")
print("-" * 65)

joblib.dump(
    ml_pipeline,
    MODEL_FILE
)

print(
    f"\nComplete pipeline saved as: {MODEL_FILE} ✅"
)


# ============================================================
# 17. LOAD SAVED PIPELINE
# ============================================================

print("\n" + "-" * 65)
print("[13] LOADING SAVED PIPELINE")
print("-" * 65)

loaded_pipeline = joblib.load(
    MODEL_FILE
)

print("\nSaved pipeline loaded successfully! ✅")


# ============================================================
# 18. TEST LOADED PIPELINE
# ============================================================

loaded_predictions = loaded_pipeline.predict(
    X_test
)

loaded_accuracy = accuracy_score(
    y_test,
    loaded_predictions
)

print(
    f"\nAccuracy of loaded pipeline: "
    f"{loaded_accuracy:.4f}"
)


# ============================================================
# 19. SAMPLE PREDICTION
# ============================================================

print("\n" + "-" * 65)
print("[14] SAMPLE PREDICTION")
print("-" * 65)

sample = X_test.iloc[[0]]

prediction = loaded_pipeline.predict(
    sample
)[0]

probabilities = loaded_pipeline.predict_proba(
    sample
)[0]

print("\nActual class:")
print(
    wine.target_names[y_test.iloc[0]]
)

print("\nPredicted class:")
print(
    wine.target_names[prediction]
)

print("\nPrediction probabilities:")

for class_index, probability in enumerate(probabilities):
    print(
        f"{wine.target_names[class_index]}: "
        f"{probability:.4f}"
    )


# ============================================================
# 20. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("DAY 27 — PIPELINE COMPLETED SUCCESSFULLY 🚀")
print("=" * 65)

print("""
Complete ML workflow:

1. Built-in dataset loading
2. Data understanding
3. Exploratory analysis
4. Train-test split
5. Missing-value handling
6. Feature scaling
7. Pipeline creation
8. Model training
9. Prediction
10. Model evaluation
11. Classification report
12. Confusion matrix
13. Result export
14. Model serialization
15. Pipeline loading
16. Sample prediction

No external dataset download required! ✅
""")

print("Day 27 completed! 🎯")