# -*- coding: utf-8 -*-
"""day18_pca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAuhkUOhmz1uXDbF8B0zEJRCuYC9wHit
"""

# ============================================================
# DAY 18 - PCA (PRINCIPAL COMPONENT ANALYSIS)
# Dataset: Breast Cancer Wisconsin
# Model: Logistic Regression
# Technique: PCA for Dimensionality Reduction
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. PROJECT INTRODUCTION
# ============================================================

print("=" * 65)
print("DAY 18 - PRINCIPAL COMPONENT ANALYSIS (PCA)")
print("=" * 65)

print("""
PCA is a dimensionality reduction technique.

It transforms a large number of correlated features
into a smaller number of principal components while
retaining as much important information as possible.
""")


# ============================================================
# 2. LOAD DATASET
# ============================================================

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("\nDataset Shape:")
print(X.shape)

print("\nNumber of Original Features:")
print(X.shape[1])

print("\nFirst 5 Rows:")
print(X.head())


# ============================================================
# 3. TARGET DISTRIBUTION
# ============================================================

print("\n" + "=" * 65)
print("TARGET DISTRIBUTION")
print("=" * 65)

print(
    y.value_counts()
)

print("\nTarget Names:")
print(data.target_names)


# ============================================================
# 4. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples :", len(X_test))


# ============================================================
# 5. STANDARDIZE FEATURES
# ============================================================

print("\n" + "=" * 65)
print("FEATURE SCALING")
print("=" * 65)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

print(
    "Features standardized successfully."
)


# ============================================================
# 6. BASELINE MODEL WITHOUT PCA
# ============================================================

print("\n" + "=" * 65)
print("BASELINE MODEL - WITHOUT PCA")
print("=" * 65)

baseline_model = LogisticRegression(
    max_iter=1000
)

baseline_model.fit(
    X_train_scaled,
    y_train
)

baseline_pred = baseline_model.predict(
    X_test_scaled
)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_pred
)

print(
    f"Baseline Accuracy: "
    f"{baseline_accuracy:.4f}"
)


# ============================================================
# 7. APPLY PCA
# ============================================================

print("\n" + "=" * 65)
print("APPLYING PCA")
print("=" * 65)

pca_full = PCA()

X_train_pca_full = pca_full.fit_transform(
    X_train_scaled
)

X_test_pca_full = pca_full.transform(
    X_test_scaled
)

print(
    "Original Number of Features:",
    X_train_scaled.shape[1]
)

print(
    "Number of PCA Components:",
    X_train_pca_full.shape[1]
)


# ============================================================
# 8. EXPLAINED VARIANCE RATIO
# ============================================================

explained_variance = (
    pca_full.explained_variance_ratio_
)

print("\nExplained Variance Ratio:")

for i, variance in enumerate(
    explained_variance,
    start=1
):
    print(
        f"PC{i}: {variance:.4f}"
    )


# ============================================================
# 9. CUMULATIVE EXPLAINED VARIANCE
# ============================================================

cumulative_variance = (
    explained_variance.cumsum()
)

print("\nCumulative Explained Variance:")

for i, variance in enumerate(
    cumulative_variance,
    start=1
):
    print(
        f"First {i} Components: "
        f"{variance:.4f}"
    )


# ============================================================
# 10. EXPLAINED VARIANCE PLOT
# ============================================================

plt.figure(
    figsize=(10, 6)
)

plt.plot(
    range(
        1,
        len(cumulative_variance) + 1
    ),
    cumulative_variance,
    marker="o"
)

plt.axhline(
    y=0.90,
    linestyle="--",
    label="90% Variance"
)

plt.axhline(
    y=0.95,
    linestyle="--",
    label="95% Variance"
)

plt.xlabel(
    "Number of Principal Components"
)

plt.ylabel(
    "Cumulative Explained Variance"
)

plt.title(
    "PCA - Cumulative Explained Variance"
)

plt.legend()

plt.grid(
    True,
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ============================================================
# 11. FIND COMPONENTS FOR 95% VARIANCE
# ============================================================

n_components_95 = (
    cumulative_variance >= 0.95
).argmax() + 1

print("\n" + "=" * 65)

print(
    "COMPONENT SELECTION"
)

print("=" * 65)

print(
    "Components required for 95% variance:",
    n_components_95
)


# ============================================================
# 12. APPLY PCA WITH SELECTED COMPONENTS
# ============================================================

pca = PCA(
    n_components=n_components_95
)

X_train_reduced = pca.fit_transform(
    X_train_scaled
)

X_test_reduced = pca.transform(
    X_test_scaled
)

print(
    "\nOriginal Feature Count:",
    X_train_scaled.shape[1]
)

print(
    "Reduced Feature Count:",
    X_train_reduced.shape[1]
)


# ============================================================
# 13. TRAIN LOGISTIC REGRESSION AFTER PCA
# ============================================================

print("\n" + "=" * 65)
print("LOGISTIC REGRESSION WITH PCA")
print("=" * 65)

pca_model = LogisticRegression(
    max_iter=1000
)

pca_model.fit(
    X_train_reduced,
    y_train
)

pca_pred = pca_model.predict(
    X_test_reduced
)

pca_accuracy = accuracy_score(
    y_test,
    pca_pred
)

print(
    f"PCA Model Accuracy: "
    f"{pca_accuracy:.4f}"
)


# ============================================================
# 14. MODEL COMPARISON
# ============================================================

print("\n" + "=" * 65)
print("MODEL COMPARISON")
print("=" * 65)

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression\nWithout PCA",
        "Logistic Regression\nWith PCA"
    ],
    "Accuracy": [
        baseline_accuracy,
        pca_accuracy
    ]
})

print(
    comparison.to_string(
        index=False
    )
)


# ============================================================
# 15. ACCURACY COMPARISON PLOT
# ============================================================

plt.figure(
    figsize=(8, 5)
)

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(
    0,
    1
)

plt.ylabel(
    "Accuracy"
)

plt.title(
    "Model Performance Before vs After PCA"
)

plt.tight_layout()

plt.show()


# ============================================================
# 16. 2D PCA VISUALIZATION
# ============================================================

pca_2d = PCA(
    n_components=2
)

X_2d = pca_2d.fit_transform(
    X_train_scaled
)

plt.figure(
    figsize=(9, 6)
)

plt.scatter(
    X_2d[y_train == 0, 0],
    X_2d[y_train == 0, 1],
    label=data.target_names[0],
    alpha=0.7
)

plt.scatter(
    X_2d[y_train == 1, 0],
    X_2d[y_train == 1, 1],
    label=data.target_names[1],
    alpha=0.7
)

plt.xlabel(
    "Principal Component 1"
)

plt.ylabel(
    "Principal Component 2"
)

plt.title(
    "2D PCA Visualization"
)

plt.legend()

plt.grid(
    True,
    alpha=0.3
)

plt.tight_layout()

plt.show()


# ============================================================
# 17. PCA COMPONENT INFORMATION
# ============================================================

print("\n" + "=" * 65)
print("PCA COMPONENT INFORMATION")
print("=" * 65)

pca_information = pd.DataFrame({
    "Component": [
        f"PC{i}"
        for i in range(
            1,
            len(pca.explained_variance_ratio_) + 1
        )
    ],
    "Explained Variance": (
        pca.explained_variance_ratio_
    ),
    "Cumulative Variance": (
        pca.explained_variance_ratio_.cumsum()
    )
})

display(
    pca_information.head(10)
)


# ============================================================
# 18. CONFUSION MATRIX
# ============================================================

print("\n" + "=" * 65)
print("CONFUSION MATRIX - PCA MODEL")
print("=" * 65)

cm = confusion_matrix(
    y_test,
    pca_pred
)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=data.target_names
)

disp.plot()

plt.title(
    "PCA Logistic Regression - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 19. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 65)
print("CLASSIFICATION REPORT - PCA MODEL")
print("=" * 65)

print(
    classification_report(
        y_test,
        pca_pred,
        target_names=data.target_names
    )
)


# ============================================================
# 20. FEATURE REDUCTION SUMMARY
# ============================================================

reduction_percentage = (
    1 -
    (
        X_train_reduced.shape[1] /
        X_train_scaled.shape[1]
    )
) * 100

print("\n" + "=" * 65)
print("FEATURE REDUCTION SUMMARY")
print("=" * 65)

print(
    "Original Features:",
    X_train_scaled.shape[1]
)

print(
    "PCA Components:",
    X_train_reduced.shape[1]
)

print(
    f"Feature Reduction: "
    f"{reduction_percentage:.2f}%"
)

print(
    f"Variance Retained: "
    f"{pca.explained_variance_ratio_.sum():.4f}"
)


# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 65)
print("DAY 18 - FINAL SUMMARY")
print("=" * 65)

print(
    f"Baseline Accuracy : "
    f"{baseline_accuracy:.4f}"
)

print(
    f"PCA Accuracy      : "
    f"{pca_accuracy:.4f}"
)

print(
    f"Original Features : "
    f"{X_train_scaled.shape[1]}"
)

print(
    f"Reduced Features  : "
    f"{X_train_reduced.shape[1]}"
)

print(
    f"Variance Retained : "
    f"{pca.explained_variance_ratio_.sum():.4f}"
)

print(
    "\nDay 18 PCA Complete! 🚀"
)

print("=" * 65)