# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19T7Myvmb3UL8edbny-QIjCZ009bDNrkJ
"""

"""
Day 3 - NumPy for Machine Learning
30 Days of Machine Learning Challenge
"""

import numpy as np


# ==========================================
# 1. NumPy Version
# ==========================================

print("NumPy Version:", np.__version__)


# ==========================================
# 2. Create Array
# ==========================================

arr = np.array([10, 20, 30, 40, 50])

print("\nArray:")
print(arr)


# ==========================================
# 3. 1D Array
# ==========================================

print("\n1D Array:")
print(arr)

print("Dimensions:", arr.ndim)


# ==========================================
# 4. 2D Array
# ==========================================

arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\n2D Array:")
print(arr_2d)

print("Dimensions:", arr_2d.ndim)


# ==========================================
# 5. Shape, Size and Data Type
# ==========================================

print("\nShape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Data Type:", arr_2d.dtype)


# ==========================================
# 6. Indexing
# ==========================================

print("\nFirst Element:", arr[0])
print("Third Element:", arr[2])
print("Last Element:", arr[-1])


# ==========================================
# 7. Slicing
# ==========================================

print("\nSliced Array:")
print(arr[1:4])


# ==========================================
# 8. Mathematical Operations
# ==========================================

print("\nAddition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 2)


# ==========================================
# 9. Statistical Operations
# ==========================================

marks = np.array([60, 70, 80, 90, 100])

print("\nMarks:", marks)
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Standard Deviation:", np.std(marks))
print("Total:", np.sum(marks))


# ==========================================
# 10. Reshaping
# ==========================================

numbers = np.array([1, 2, 3, 4, 5, 6])

reshaped = numbers.reshape(2, 3)

print("\nReshaped Array:")
print(reshaped)


# ==========================================
# 11. Zeros and Ones
# ==========================================

print("\nZeros:")
print(np.zeros((2, 3)))

print("\nOnes:")
print(np.ones((2, 3)))


# ==========================================
# 12. Range
# ==========================================

print("\nRange:")
print(np.arange(1, 11))


# ==========================================
# 13. Random Numbers
# ==========================================

np.random.seed(42)

random_numbers = np.random.randint(1, 100, 5)

print("\nRandom Numbers:")
print(random_numbers)

