# -*- coding: utf-8 -*-
"""Day9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiQAXMSgoaD6rOpuSUOi1p_k6NPfo6cq
"""

"""
Day 9 - K-Nearest Neighbors (KNN)
30 Days of Machine Learning Challenge

Dataset:
StudentPerformanceFactors.csv

Goal:
Predict whether a student has High or Low Performance.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# ==========================================
# 1. Load Dataset
# ==========================================

df = pd.read_csv(
    "StudentPerformanceFactors.csv"
)

print("First 5 Records:")
print(df.head())


# ==========================================
# 2. Explore Dataset
# ==========================================

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())


# ==========================================
# 3. Create Classification Target
# ==========================================

# 1 = High Performance
# 0 = Low Performance

df["Performance"] = (
    df["Exam_Score"] >= 75
).astype(int)

print("\nPerformance Distribution:")
print(df["Performance"].value_counts())


# ==========================================
# 4. Visualize Class Distribution
# ==========================================

plt.figure(figsize=(6, 4))

sns.countplot(
    x="Performance",
    data=df
)

plt.title("Performance Class Distribution")
plt.xlabel("Performance (0 = Low, 1 = High)")
plt.ylabel("Number of Students")

plt.tight_layout()
plt.show()


# ==========================================
# 5. Select Features and Target
# ==========================================

features = [
    "Hours_Studied",
    "Attendance",
    "Previous_Scores",
    "Sleep_Hours",
    "Tutoring_Sessions"
]

X = df[features]

y = df["Performance"]

print("\nSelected Features:")
print(X.head())

print("\nTarget:")
print(y.head())


# ==========================================
# 6. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)


# ==========================================
# 7. Feature Scaling
# ==========================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

print("\nFeature Scaling Completed!")


# ==========================================
# 8. Create KNN Model
# ==========================================

knn = KNeighborsClassifier(
    n_neighbors=5
)


# ==========================================
# 9. Train KNN Model
# ==========================================

knn.fit(
    X_train_scaled,
    y_train
)

print("KNN Model Training Completed!")


# ==========================================
# 10. Make Predictions
# ==========================================

y_pred = knn.predict(
    X_test_scaled
)

print("\nFirst 20 Predictions:")
print(y_pred[:20])


# ==========================================
# 11. Model Evaluation
# ==========================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred
)

recall = recall_score(
    y_test,
    y_pred
)

f1 = f1_score(
    y_test,
    y_pred
)

print("\nKNN Model Evaluation")
print("-------------------------")

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)


# ==========================================
# 12. Classification Report
# ==========================================

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred
    )
)


# ==========================================
# 13. Confusion Matrix
# ==========================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)


# ==========================================
# 14. Confusion Matrix Visualization
# ==========================================

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.title("KNN Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.tight_layout()
plt.show()


# ==========================================
# 15. Test Different K Values
# ==========================================

k_values = range(1, 21)

accuracies = []

for k in k_values:

    model = KNeighborsClassifier(
        n_neighbors=k
    )

    model.fit(
        X_train_scaled,
        y_train
    )

    prediction = model.predict(
        X_test_scaled
    )

    score = accuracy_score(
        y_test,
        prediction
    )

    accuracies.append(score)


# ==========================================
# 16. K vs Accuracy Plot
# ==========================================

plt.figure(figsize=(9, 5))

plt.plot(
    k_values,
    accuracies,
    marker="o"
)

plt.xlabel("Number of Neighbors (K)")
plt.ylabel("Accuracy")
plt.title("K Value vs Accuracy")

plt.xticks(
    list(k_values)
)

plt.tight_layout()
plt.show()


# ==========================================
# 17. Find Best K
# ==========================================

best_k = k_values[
    accuracies.index(
        max(accuracies)
    )
]

best_accuracy = max(
    accuracies
)

print("\nBest K:", best_k)
print("Best Accuracy:", best_accuracy)


# ==========================================
# 18. Train Final KNN Model
# ==========================================

best_knn = KNeighborsClassifier(
    n_neighbors=best_k
)

best_knn.fit(
    X_train_scaled,
    y_train
)


# ==========================================
# 19. Predict New Student
# ==========================================

new_student = pd.DataFrame({
    "Hours_Studied": [6],
    "Attendance": [90],
    "Previous_Scores": [75],
    "Sleep_Hours": [7],
    "Tutoring_Sessions": [2]
})


# Scale new data using the same scaler
new_student_scaled = scaler.transform(
    new_student
)


# Make prediction
prediction = best_knn.predict(
    new_student_scaled
)


# Get probability
probability = best_knn.predict_proba(
    new_student_scaled
)


# ==========================================
# 20. Display Prediction
# ==========================================

if prediction[0] == 1:

    print("\nPredicted Performance: HIGH")

else:

    print("\nPredicted Performance: LOW")


print("\nPrediction Probability:")
print(probability)


# ==========================================
# 21. Final Summary
# ==========================================

print("\n================================")
print("================================")

print("Algorithm: K-Nearest Neighbors")
print("Best K:", best_k)
print("Best Accuracy:", best_accuracy)
print("Features Used:", features)
print("Target: Performance")

