# -*- coding: utf-8 -*-
"""Day14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5nkmhTWrvQgGtbbTxvm6lbQgXC7RcVJ
"""

# ============================================================
# DAY 14 - SVM HYPERPARAMETER TUNING
# GridSearchCV + Cross Validation
# Dataset: Breast Cancer Dataset
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("=" * 60)
print("DAY 14 - SVM HYPERPARAMETER TUNING")
print("=" * 60)

print("\nDataset Shape:")
print(X.shape)

print("\nTarget Classes:")
print(data.target_names)

print("\nClass Distribution:")
print(y.value_counts())


# ============================================================
# 2. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", X_train.shape[0])
print("Testing Samples :", X_test.shape[0])


# ============================================================
# 3. BASELINE SVM
# ============================================================

print("\n" + "=" * 60)
print("BASELINE SVM")
print("=" * 60)

baseline_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        C=1,
        gamma="scale"
    ))
])

baseline_model.fit(
    X_train,
    y_train
)

baseline_pred = baseline_model.predict(
    X_test
)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_pred
)

print(
    f"\nBaseline SVM Accuracy: "
    f"{baseline_accuracy:.4f}"
)


# ============================================================
# 4. DEFINE HYPERPARAMETER GRID
# ============================================================

print("\n" + "=" * 60)
print("HYPERPARAMETERS")
print("=" * 60)

param_grid = {

    "svm__C": [
        0.1,
        1,
        10,
        100
    ],

    "svm__kernel": [
        "linear",
        "rbf",
        "poly"
    ],

    "svm__gamma": [
        "scale",
        "auto"
    ]
}

print("\nC values:")
print(param_grid["svm__C"])

print("\nKernels:")
print(param_grid["svm__kernel"])

print("\nGamma values:")
print(param_grid["svm__gamma"])


# ============================================================
# 5. GRIDSEARCHCV
# ============================================================

print("\n" + "=" * 60)
print("GRIDSEARCHCV")
print("=" * 60)

grid_search = GridSearchCV(
    estimator=baseline_model,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

print("\nTraining GridSearchCV...")

grid_search.fit(
    X_train,
    y_train
)


# ============================================================
# 6. BEST PARAMETERS
# ============================================================

print("\n" + "=" * 60)
print("BEST PARAMETERS")
print("=" * 60)

print("\nBest Parameters:")

print(
    grid_search.best_params_
)

print(
    "\nBest Cross-Validation Accuracy:"
)

print(
    f"{grid_search.best_score_:.4f}"
)


# ============================================================
# 7. BEST MODEL
# ============================================================

best_model = grid_search.best_estimator_

tuned_pred = best_model.predict(
    X_test
)

tuned_accuracy = accuracy_score(
    y_test,
    tuned_pred
)

print("\nTuned SVM Test Accuracy:")

print(
    f"{tuned_accuracy:.4f}"
)


# ============================================================
# 8. COMPARE BASELINE VS TUNED
# ============================================================

print("\n" + "=" * 60)
print("BASELINE VS TUNED SVM")
print("=" * 60)

improvement = (
    tuned_accuracy -
    baseline_accuracy
)

comparison = pd.DataFrame({

    "Model": [
        "Baseline SVM",
        "Tuned SVM"
    ],

    "Accuracy": [
        baseline_accuracy,
        tuned_accuracy
    ]

})

print(
    comparison.to_string(
        index=False
    )
)

print(
    f"\nAccuracy Improvement: "
    f"{improvement:.4f}"
)


# ============================================================
# 9. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        tuned_pred,
        target_names=data.target_names
    )
)


# ============================================================
# 10. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    tuned_pred
)

print("\nConfusion Matrix:")

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=data.target_names
)

disp.plot()

plt.title(
    "Tuned SVM - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 11. GET GRIDSEARCH RESULTS
# ============================================================

results = pd.DataFrame(
    grid_search.cv_results_
)

results = results[
    [
        "param_svm__C",
        "param_svm__kernel",
        "param_svm__gamma",
        "mean_test_score",
        "std_test_score",
        "rank_test_score"
    ]
].sort_values(
    "rank_test_score"
)

print("\n" + "=" * 60)
print("TOP 10 HYPERPARAMETER COMBINATIONS")
print("=" * 60)

print(
    results.head(10).to_string(
        index=False
    )
)


# ============================================================
# 12. VISUALIZE TOP 10 COMBINATIONS
# ============================================================

top_results = results.head(10).copy()

top_results["parameters"] = (
    "C="
    + top_results["param_svm__C"].astype(str)
    + ", "
    + top_results["param_svm__kernel"].astype(str)
    + ", gamma="
    + top_results["param_svm__gamma"].astype(str)
)

plt.figure(
    figsize=(12, 6)
)

plt.bar(
    top_results["parameters"],
    top_results["mean_test_score"]
)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.ylabel(
    "Cross-Validation Accuracy"
)

plt.xlabel(
    "Hyperparameter Combination"
)

plt.title(
    "Top SVM Hyperparameter Combinations"
)

plt.tight_layout()

plt.show()


# ============================================================
# 13. BASELINE VS TUNED VISUALIZATION
# ============================================================

plt.figure(
    figsize=(7, 5)
)

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(
    min(0.8, comparison["Accuracy"].min() - 0.05),
    1.0
)

plt.ylabel(
    "Accuracy"
)

plt.title(
    "Baseline SVM vs Tuned SVM"
)

plt.tight_layout()

plt.show()


# ============================================================
# 14. FINAL RESULT
# ============================================================

print("\n" + "=" * 60)
print("FINAL RESULT")
print("=" * 60)

print(
    f"\nBaseline Accuracy : "
    f"{baseline_accuracy:.4f}"
)

print(
    f"Tuned Accuracy    : "
    f"{tuned_accuracy:.4f}"
)

print(
    f"Improvement       : "
    f"{improvement:.4f}"
)

print(
    "\nBest Parameters:"
)

for parameter, value in grid_search.best_params_.items():

    print(
        f"{parameter}: {value}"
    )

print("\nDay 14 SVM Hyperparameter Tuning Complete!")
print("=" * 60)