# -*- coding: utf-8 -*-
"""Day13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KKmJKLcWTO9CV_221E256lNa7Dpqsqf
"""

# ============================================================
# DAY 13 - SUPPORT VECTOR MACHINE (SVM)
# Classification using Breast Cancer Dataset
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("=" * 60)
print("DAY 13 - SUPPORT VECTOR MACHINE")
print("=" * 60)

print("\nDataset Shape:")
print(X.shape)

print("\nTarget Classes:")
print(data.target_names)

print("\nFirst 5 Rows:")
print(X.head())


# ============================================================
# 2. CHECK CLASS DISTRIBUTION
# ============================================================

print("\nClass Distribution:")
print(y.value_counts())


# ============================================================
# 3. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", X_train.shape[0])
print("Testing Samples :", X_test.shape[0])


# ============================================================
# 4. FEATURE SCALING
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)


# ============================================================
# 5. LINEAR SVM
# ============================================================

print("\n" + "=" * 60)
print("LINEAR SVM")
print("=" * 60)

linear_svm = SVC(
    kernel="linear",
    C=1
)

linear_svm.fit(
    X_train_scaled,
    y_train
)

linear_pred = linear_svm.predict(
    X_test_scaled
)

linear_accuracy = accuracy_score(
    y_test,
    linear_pred
)

print(
    f"\nLinear SVM Accuracy: "
    f"{linear_accuracy:.4f}"
)


# ============================================================
# 6. RBF / NON-LINEAR SVM
# ============================================================

print("\n" + "=" * 60)
print("RBF / NON-LINEAR SVM")
print("=" * 60)

rbf_svm = SVC(
    kernel="rbf",
    C=1,
    gamma="scale"
)

rbf_svm.fit(
    X_train_scaled,
    y_train
)

rbf_pred = rbf_svm.predict(
    X_test_scaled
)

rbf_accuracy = accuracy_score(
    y_test,
    rbf_pred
)

print(
    f"\nRBF SVM Accuracy: "
    f"{rbf_accuracy:.4f}"
)


# ============================================================
# 7. COMPARE MODELS
# ============================================================

print("\n" + "=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

comparison = pd.DataFrame({
    "Model": [
        "Linear SVM",
        "RBF SVM"
    ],

    "Accuracy": [
        linear_accuracy,
        rbf_accuracy
    ]
})

print(
    comparison.to_string(
        index=False
    )
)


# ============================================================
# 8. SELECT BEST MODEL
# ============================================================

if rbf_accuracy >= linear_accuracy:

    best_model = rbf_svm
    best_predictions = rbf_pred
    best_name = "RBF SVM"
    best_accuracy = rbf_accuracy

else:

    best_model = linear_svm
    best_predictions = linear_pred
    best_name = "Linear SVM"
    best_accuracy = linear_accuracy


print("\nBest Model:")
print(best_name)

print(
    f"Best Accuracy: "
    f"{best_accuracy:.4f}"
)


# ============================================================
# 9. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        best_predictions,
        target_names=data.target_names
    )
)


# ============================================================
# 10. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    best_predictions
)

print("\nConfusion Matrix:")
print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=data.target_names
)

disp.plot()

plt.title(
    f"{best_name} - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 11. ACCURACY COMPARISON PLOT
# ============================================================

plt.figure(
    figsize=(7, 5)
)

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(
    0.8,
    1.0
)

plt.ylabel(
    "Accuracy"
)

plt.xlabel(
    "SVM Model"
)

plt.title(
    "Linear SVM vs RBF SVM"
)

plt.tight_layout()

plt.show()


# ============================================================
# 12. FINAL RESULT
# ============================================================

print("\n" + "=" * 60)
print("FINAL RESULT")
print("=" * 60)

print(
    f"Linear SVM Accuracy : "
    f"{linear_accuracy:.4f}"
)

print(
    f"RBF SVM Accuracy    : "
    f"{rbf_accuracy:.4f}"
)

print(
    f"Best Model          : "
    f"{best_name}"
)

print(
    f"Best Accuracy       : "
    f"{best_accuracy:.4f}"
)

print("\nSVM Training Complete!")
print("=" * 60)