# -*- coding: utf-8 -*-
"""Day11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OWrTDqgHpZAmEzYgPgUSAWdTFASGDEh
"""

"""
Day 11 - Naive Bayes Classification
30 Days of Machine Learning Challenge

Dataset:
StudentPerformanceFactors.csv

Goal:
Predict whether a student belongs to:
High Performance or Low Performance
"""

# ==========================================
# 1. Import Libraries
# ==========================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


print("=" * 60)
print("DAY 11 - NAIVE BAYES CLASSIFICATION")
print("=" * 60)


# ==========================================
# 2. Load Dataset
# ==========================================

df = pd.read_csv("StudentPerformanceFactors.csv")

print("\nDataset Loaded Successfully!")

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Records:")
print(df.head())


# ==========================================
# 3. Dataset Information
# ==========================================

print("\nDataset Information:")
df.info()


# ==========================================
# 4. Missing Values
# ==========================================

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())


# ==========================================
# 5. Handle Missing Values
# ==========================================

numeric_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_columns = df.select_dtypes(
    include=["object"]
).columns


for column in numeric_columns:

    df[column] = df[column].fillna(
        df[column].median()
    )


for column in categorical_columns:

    df[column] = df[column].fillna(
        df[column].mode()[0]
    )


print("\nMissing values handled successfully!")

print(
    "Remaining Missing Values:",
    df.isnull().sum().sum()
)


# ==========================================
# 6. Create Performance Target
# ==========================================

df["Performance"] = np.where(
    df["Exam_Score"] >= 75,
    "High Performance",
    "Low Performance"
)


print("\nPerformance Distribution:")
print(
    df["Performance"].value_counts()
)


# ==========================================
# 7. Performance Visualization
# ==========================================

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="Performance"
)

plt.title(
    "Student Performance Distribution"
)

plt.xlabel("Performance")

plt.ylabel("Number of Students")

plt.tight_layout()

plt.show()


# ==========================================
# 8. Select Features
# ==========================================

features = [
    "Hours_Studied",
    "Attendance",
    "Previous_Scores",
    "Sleep_Hours",
    "Tutoring_Sessions",
    "Physical_Activity"
]


X = df[features]

y = df["Performance"]


print("\nSelected Features:")
print(X.head())

print("\nTarget:")
print(y.head())


# ==========================================
# 9. Encode Target
# ==========================================

y = y.map({
    "Low Performance": 0,
    "High Performance": 1
})


print("\nEncoded Target:")
print(y.head())

print("\nTarget Distribution:")
print(y.value_counts())


# ==========================================
# 10. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


print("\nDataset Split")
print("-" * 30)

print("Total Records:", len(X))

print("Training Records:", len(X_train))

print("Testing Records:", len(X_test))


# ==========================================
# 11. Feature Scaling
# ==========================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)


print("\nFeature scaling completed!")


# ==========================================
# 12. Create Naive Bayes Model
# ==========================================

nb_model = GaussianNB()

print("\nNaive Bayes Model:")
print(nb_model)


# ==========================================
# 13. Train Model
# ==========================================

nb_model.fit(
    X_train_scaled,
    y_train
)

print("\nNaive Bayes model trained successfully!")


# ==========================================
# 14. Predictions
# ==========================================

y_pred = nb_model.predict(
    X_test_scaled
)


print("\nFirst 20 Predictions:")
print(y_pred[:20])


# ==========================================
# 15. Prediction Probabilities
# ==========================================

y_probability = nb_model.predict_proba(
    X_test_scaled
)


print("\nFirst 10 Prediction Probabilities:")
print(y_probability[:10])


# ==========================================
# 16. Model Evaluation
# ==========================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)


print("\n" + "=" * 60)
print("NAIVE BAYES MODEL PERFORMANCE")
print("=" * 60)

print(
    f"Accuracy  : {accuracy:.4f}"
)

print(
    f"Precision : {precision:.4f}"
)

print(
    f"Recall    : {recall:.4f}"
)

print(
    f"F1 Score  : {f1:.4f}"
)


# ==========================================
# 17. Classification Report
# ==========================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "Low Performance",
            "High Performance"
        ],
        zero_division=0
    )
)


# ==========================================
# 18. Confusion Matrix
# ==========================================

cm = confusion_matrix(
    y_test,
    y_pred
)


print("\nConfusion Matrix:")
print(cm)


# ==========================================
# 19. Confusion Matrix Visualization
# ==========================================

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=[
        "Low Performance",
        "High Performance"
    ],
    yticklabels=[
        "Low Performance",
        "High Performance"
    ]
)

plt.title(
    "Naive Bayes Confusion Matrix"
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.tight_layout()

plt.show()


# ==========================================
# 20. Actual vs Predicted
# ==========================================

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})


comparison["Actual"] = comparison[
    "Actual"
].map({
    0: "Low Performance",
    1: "High Performance"
})


comparison["Predicted"] = comparison[
    "Predicted"
].map({
    0: "Low Performance",
    1: "High Performance"
})


print("\nActual vs Predicted:")
print(comparison.head(20))


# ==========================================
# 21. Test New Student
# ==========================================

new_student = pd.DataFrame({
    "Hours_Studied": [25],
    "Attendance": [95],
    "Previous_Scores": [90],
    "Sleep_Hours": [8],
    "Tutoring_Sessions": [3],
    "Physical_Activity": [4]
})


new_student_scaled = scaler.transform(
    new_student
)


prediction = nb_model.predict(
    new_student_scaled
)


probability = nb_model.predict_proba(
    new_student_scaled
)


if prediction[0] == 1:

    result = "High Performance"

else:

    result = "Low Performance"


confidence = probability[
    0
][prediction[0]]


print("\n" + "=" * 60)
print("NEW STUDENT PREDICTION")
print("=" * 60)

print(
    "Prediction:",
    result
)

print(
    f"Confidence: {confidence * 100:.2f}%"
)


# ==========================================
# 22. Prediction Probability Visualization
# ==========================================

classes = [
    "Low Performance",
    "High Performance"
]

probabilities = probability[0]


plt.figure(figsize=(8, 5))

plt.bar(
    classes,
    probabilities
)

plt.title(
    "Naive Bayes Prediction Probability"
)

plt.xlabel(
    "Performance Category"
)

plt.ylabel(
    "Probability"
)

plt.ylim(0, 1)

plt.tight_layout()

plt.show()


# ==========================================
# 23. Final Summary
# ==========================================

print("\n" + "=" * 60)
print("DAY 11 - FINAL SUMMARY")
print("=" * 60)

print(
    "Dataset Size:",
    df.shape
)

print(
    "Training Records:",
    len(X_train)
)

print(
    "Testing Records:",
    len(X_test)
)

print(
    f"Accuracy: {accuracy:.4f}"
)

print(
    f"Precision: {precision:.4f}"
)

print(
    f"Recall: {recall:.4f}"
)

print(
    f"F1 Score: {f1:.4f}"
)

print("=" * 60)

print("\nDay 11 completed successfully! 🚀")