# -*- coding: utf-8 -*-
"""Day10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtyDL3leX25AcWF8UCxRw5RA5Gg_fKf0
"""

# ============================================================
# DAY 10 - DECISION TREE CLASSIFICATION
# 30 Days Machine Learning Challenge
# Student Performance Dataset
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

df = pd.read_csv("/content/StudentPerformanceFactors.csv")

print("=" * 60)
print("STUDENT PERFORMANCE DATASET")
print("=" * 60)

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Columns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 2. DATA INFORMATION
# ============================================================

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())


# ============================================================
# 3. REMOVE DUPLICATES
# ============================================================

df = df.drop_duplicates()

print("\nShape after removing duplicates:")
print(df.shape)


# ============================================================
# 4. CREATE TARGET VARIABLE
# ============================================================

# The dataset does not contain a Pass/Fail column.
# We create one using the median Exam Score.

median_score = df["Exam_Score"].median()

df["Pass"] = (
    df["Exam_Score"] >= median_score
).astype(int)

print("\nMedian Exam Score:")
print(median_score)

print("\nPass/Fail Distribution:")
print(df["Pass"].value_counts())

print("\nUnique Target Classes:")
print(df["Pass"].unique())


# ============================================================
# 5. SELECT FEATURES
# ============================================================

X = df[
    [
        "Hours_Studied",
        "Attendance",
        "Previous_Scores",
        "Sleep_Hours",
        "Tutoring_Sessions",
        "Physical_Activity"
    ]
]

y = df["Pass"]


print("\nFeatures:")
print(X.head())

print("\nTarget:")
print(y.head())


# ============================================================
# 6. CHECK TARGET DISTRIBUTION
# ============================================================

print("\nTarget Distribution:")
print(y.value_counts())


# Make sure both classes exist
if y.nunique() < 2:
    raise ValueError(
        "The target contains only one class. "
        "Decision Tree Classification requires at least two classes."
    )


# ============================================================
# 7. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 8. CREATE DECISION TREE MODEL
# ============================================================

model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42
)


# ============================================================
# 9. TRAIN MODEL
# ============================================================

model.fit(X_train, y_train)

print("\nDecision Tree Model Trained Successfully!")


# ============================================================
# 10. MAKE PREDICTIONS
# ============================================================

y_pred = model.predict(X_test)

print("\nFirst 20 Predictions:")
print(y_pred[:20])

print("\nFirst 20 Actual Values:")
print(y_test.values[:20])


# ============================================================
# 11. ACCURACY
# ============================================================

accuracy = accuracy_score(y_test, y_pred)

print("\n" + "=" * 60)
print("MODEL EVALUATION")
print("=" * 60)

print(f"\nAccuracy: {accuracy:.4f}")
print(f"Accuracy Percentage: {accuracy * 100:.2f}%")


# ============================================================
# 12. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=[0, 1]
)

print("\nConfusion Matrix:")
print(cm)


# ============================================================
# 13. CONFUSION MATRIX VISUALIZATION
# ============================================================

plt.figure(figsize=(6, 5))

plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks(
    [0, 1],
    ["Fail", "Pass"]
)

plt.yticks(
    [0, 1],
    ["Fail", "Pass"]
)

for i in range(2):
    for j in range(2):
        plt.text(
            j,
            i,
            cm[i, j],
            ha="center",
            va="center"
        )

plt.show()


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        labels=[0, 1],
        target_names=["Fail", "Pass"],
        zero_division=0
    )
)


# ============================================================
# 15. FEATURE IMPORTANCE
# ============================================================

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance:")
print(importance)


# ============================================================
# 16. FEATURE IMPORTANCE VISUALIZATION
# ============================================================

plt.figure(figsize=(8, 6))

plt.bar(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()


# ============================================================
# 17. VISUALIZE DECISION TREE
# ============================================================

plt.figure(figsize=(16, 8))

plot_tree(
    model,
    feature_names=X.columns,
    class_names=["Fail", "Pass"],
    filled=True
)

plt.title("Student Performance Decision Tree")

plt.show()


# ============================================================
# 18. PREDICT A NEW STUDENT
# ============================================================

new_student = pd.DataFrame({
    "Hours_Studied": [6],
    "Attendance": [85],
    "Previous_Scores": [70],
    "Sleep_Hours": [7],
    "Tutoring_Sessions": [2],
    "Physical_Activity": [3]
})

prediction = model.predict(new_student)

print("\n" + "=" * 60)
print("NEW STUDENT PREDICTION")
print("=" * 60)

if prediction[0] == 1:
    print("Prediction: Student is likely to PASS")
else:
    print("Prediction: Student is likely to FAIL")


# ============================================================
# 19. CHECK TRAINING VS TESTING ACCURACY
# ============================================================

train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print("\nTraining Accuracy:")
print(f"{train_accuracy * 100:.2f}%")

print("\nTesting Accuracy:")
print(f"{test_accuracy * 100:.2f}%")


# ============================================================
# END
# ============================================================

print("\n" + "=" * 60)
print("DAY 10 - DECISION TREE CLASSIFICATION COMPLETED")
print("=" * 60)