# -*- coding: utf-8 -*-
"""day22_hyperparameter_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNfcNg7uPBvdBccRLJyre0LxundTLwrF
"""

# ============================================================
# DAY 22 - HYPERPARAMETER TUNING
# Model: Random Forest Classifier
# Dataset: Breast Cancer Wisconsin Dataset
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. PROJECT INTRODUCTION
# ============================================================

print("=" * 65)
print("DAY 22 - HYPERPARAMETER TUNING")
print("=" * 65)

print("""
Hyperparameter tuning is the process of finding the best
configuration of a machine learning model.

In this project, GridSearchCV is used to find better
hyperparameters for a Random Forest Classifier.
""")


# ============================================================
# 2. LOAD DATASET
# ============================================================

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("\nDataset Shape:")
print(X.shape)

print("\nFirst 5 Rows:")
print(X.head())


# ============================================================
# 3. TARGET INFORMATION
# ============================================================

print("\n" + "=" * 65)
print("TARGET INFORMATION")
print("=" * 65)

print("\nTarget Classes:")
print(data.target_names)

print("\nTarget Distribution:")
print(y.value_counts())


# ============================================================
# 4. TRAIN-TEST SPLIT
# ============================================================

print("\n" + "=" * 65)
print("TRAIN-TEST SPLIT")
print("=" * 65)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Samples:", len(X_train))
print("Testing Samples :", len(X_test))


# ============================================================
# 5. BASELINE RANDOM FOREST
# ============================================================

print("\n" + "=" * 65)
print("BASELINE RANDOM FOREST")
print("=" * 65)

baseline_model = RandomForestClassifier(
    random_state=42
)

baseline_model.fit(
    X_train,
    y_train
)

baseline_predictions = baseline_model.predict(
    X_test
)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_predictions
)

print(
    f"Baseline Accuracy: "
    f"{baseline_accuracy:.4f}"
)


# ============================================================
# 6. DEFINE HYPERPARAMETER GRID
# ============================================================

print("\n" + "=" * 65)
print("HYPERPARAMETER GRID")
print("=" * 65)

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt", "log2"]
}

print("\nParameters to tune:")

for parameter, values in param_grid.items():
    print(
        f"{parameter}: {values}"
    )


# ============================================================
# 7. GRIDSEARCHCV
# ============================================================

print("\n" + "=" * 65)
print("RUNNING GRIDSEARCHCV")
print("=" * 65)

rf_model = RandomForestClassifier(
    random_state=42
)

grid_search = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

grid_search.fit(
    X_train,
    y_train
)
# ============================================================
# 8. BEST PARAMETERS
# ============================================================

print("\n" + "=" * 65)
print("BEST HYPERPARAMETERS")
print("=" * 65)

print(
    grid_search.best_params_
)
# ============================================================
# 9. BEST CROSS-VALIDATION SCORE
# ============================================================

print("\n" + "=" * 65)
print("BEST CROSS-VALIDATION SCORE")
print("=" * 65)

print(
    f"Best CV Accuracy: "
    f"{grid_search.best_score_:.4f}"
)
# ============================================================
# 10. BEST MODEL
# ============================================================

best_model = grid_search.best_estimator_

print("\nBest model created successfully.")


# ============================================================
# 11. TEST SET PREDICTION
# ============================================================

tuned_predictions = best_model.predict(
    X_test
)

tuned_accuracy = accuracy_score(
    y_test,
    tuned_predictions
)

print("\n" + "=" * 65)
print("TUNED MODEL PERFORMANCE")
print("=" * 65)

print(
    f"Tuned Model Accuracy: "
    f"{tuned_accuracy:.4f}"
)


# ============================================================
# 12. COMPARE BASELINE VS TUNED MODEL
# ============================================================

print("\n" + "=" * 65)
print("MODEL COMPARISON")
print("=" * 65)

accuracy_comparison = pd.DataFrame({
    "Model": [
        "Baseline Random Forest",
        "Tuned Random Forest"
    ],

    "Accuracy": [
        baseline_accuracy,
        tuned_accuracy
    ]
})

accuracy_comparison["Accuracy"] = (
    accuracy_comparison["Accuracy"]
    .round(4)
)

print(
    accuracy_comparison
)


# ============================================================
# 13. ACCURACY IMPROVEMENT
# ============================================================

improvement = (
    tuned_accuracy -
    baseline_accuracy
)

print(
    f"\nAccuracy Improvement: "
    f"{improvement:.4f}"
)


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 65)
print("CLASSIFICATION REPORT")
print("=" * 65)

print(
    classification_report(
        y_test,
        tuned_predictions,
        target_names=data.target_names
    )
)


# ============================================================
# 15. CONFUSION MATRIX
# ============================================================

print("\n" + "=" * 65)
print("CONFUSION MATRIX")
print("=" * 65)

cm = confusion_matrix(
    y_test,
    tuned_predictions
)

print(cm)

display_labels = data.target_names

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=display_labels
)

disp.plot()

plt.title(
    "Tuned Random Forest - Confusion Matrix"
)

plt.tight_layout()
plt.show()


# ============================================================
# 16. FEATURE IMPORTANCE
# ============================================================

print("\n" + "=" * 65)
print("FEATURE IMPORTANCE")
print("=" * 65)

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": best_model.feature_importances_
})

feature_importance = (
    feature_importance
    .sort_values(
        by="Importance",
        ascending=False
    )
)

print(
    feature_importance.head(10)
)


# ============================================================
# 17. TOP FEATURE IMPORTANCES VISUALIZATION
# ============================================================

top_features = feature_importance.head(10)

plt.figure(figsize=(6, 4))

plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title(
    "Top 10 Random Forest Feature Importances"
)

plt.tight_layout()
plt.show()


# ============================================================
# 18. FINAL RESULTS
# ============================================================

print("\n" + "=" * 65)
print("DAY 22 - FINAL RESULTS")
print("=" * 65)

print(
    f"Baseline Accuracy : "
    f"{baseline_accuracy:.4f}"
)

print(
    f"Tuned Accuracy    : "
    f"{tuned_accuracy:.4f}"
)

print(
    f"Best CV Accuracy  : "
    f"{grid_search.best_score_:.4f}"
)

print(
    f"Improvement       : "
    f"{improvement:.4f}"
)

print("\nBest Hyperparameters:")

for parameter, value in (
    grid_search.best_params_.items()
):
    print(
        f"{parameter}: {value}"
    )

print(
    "\nDay 22 Hyperparameter Tuning Complete! 🚀"
)

print("=" * 65)