# -*- coding: utf-8 -*-
"""day17_feature_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKwtmVKYKLvFZAfH5GxeV8gGhF3xgWxo
"""

# ============================================================
# DAY 17 - FEATURE SCALING
# Dataset: Breast Cancer Wisconsin
# Models: KNN
# Techniques: StandardScaler vs MinMaxScaler
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

print("=" * 60)
print("DAY 17 - FEATURE SCALING")
print("=" * 60)

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = pd.Series(
    data.target,
    name="target"
)

print("\nDataset Shape:")
print(X.shape)

print("\nFirst 5 Rows:")
print(X.head())


# ============================================================
# 2. EXPLORE FEATURE RANGES
# ============================================================

print("\n" + "=" * 60)
print("FEATURE RANGES BEFORE SCALING")
print("=" * 60)

feature_ranges = pd.DataFrame({
    "Minimum": X.min(),
    "Maximum": X.max(),
    "Mean": X.mean(),
    "Std": X.std()
})

print(
    feature_ranges.head(10)
)


# ============================================================
# 3. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples :", len(X_test))


# ============================================================
# 4. MODEL WITHOUT SCALING
# ============================================================

print("\n" + "=" * 60)
print("KNN WITHOUT FEATURE SCALING")
print("=" * 60)

knn_unscaled = KNeighborsClassifier(
    n_neighbors=5
)

knn_unscaled.fit(
    X_train,
    y_train
)

pred_unscaled = knn_unscaled.predict(
    X_test
)

accuracy_unscaled = accuracy_score(
    y_test,
    pred_unscaled
)

print(
    f"Accuracy without scaling: "
    f"{accuracy_unscaled:.4f}"
)


# ============================================================
# 5. STANDARDIZATION
# ============================================================

print("\n" + "=" * 60)
print("STANDARDIZATION - StandardScaler")
print("=" * 60)

standard_scaler = StandardScaler()

X_train_standard = standard_scaler.fit_transform(
    X_train
)

X_test_standard = standard_scaler.transform(
    X_test
)

print("\nFirst 5 Standardized Rows:")

print(
    X_train_standard[:5]
)


# ============================================================
# 6. KNN WITH STANDARDIZATION
# ============================================================

knn_standard = KNeighborsClassifier(
    n_neighbors=5
)

knn_standard.fit(
    X_train_standard,
    y_train
)

pred_standard = knn_standard.predict(
    X_test_standard
)

accuracy_standard = accuracy_score(
    y_test,
    pred_standard
)

print(
    f"\nAccuracy with StandardScaler: "
    f"{accuracy_standard:.4f}"
)


# ============================================================
# 7. MIN-MAX NORMALIZATION
# ============================================================

print("\n" + "=" * 60)
print("NORMALIZATION - MinMaxScaler")
print("=" * 60)

minmax_scaler = MinMaxScaler()

X_train_minmax = minmax_scaler.fit_transform(
    X_train
)

X_test_minmax = minmax_scaler.transform(
    X_test
)

print("\nFirst 5 Min-Max Scaled Rows:")

print(
    X_train_minmax[:5]
)


# ============================================================
# 8. KNN WITH MIN-MAX SCALING
# ============================================================

knn_minmax = KNeighborsClassifier(
    n_neighbors=5
)

knn_minmax.fit(
    X_train_minmax,
    y_train
)

pred_minmax = knn_minmax.predict(
    X_test_minmax
)

accuracy_minmax = accuracy_score(
    y_test,
    pred_minmax
)

print(
    f"\nAccuracy with MinMaxScaler: "
    f"{accuracy_minmax:.4f}"
)


# ============================================================
# 9. COMPARE RESULTS
# ============================================================

print("\n" + "=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

comparison = pd.DataFrame({
    "Method": [
        "Without Scaling",
        "StandardScaler",
        "MinMaxScaler"
    ],
    "Accuracy": [
        accuracy_unscaled,
        accuracy_standard,
        accuracy_minmax
    ]
})

print(
    comparison.to_string(
        index=False
    )
)


# ============================================================
# 10. VISUALIZE COMPARISON
# ============================================================

plt.figure(
    figsize=(7, 5)
)

plt.bar(
    comparison["Method"],
    comparison["Accuracy"]
)

plt.ylim(
    0,
    1
)

plt.ylabel(
    "Accuracy"
)

plt.xlabel(
    "Scaling Method"
)

plt.title(
    "KNN Performance: Feature Scaling Comparison"
)

plt.tight_layout()

plt.show()


# ============================================================
# 11. VISUALIZE FEATURE DISTRIBUTION BEFORE SCALING
# ============================================================

plt.figure(
    figsize=(6, 4)
)

X[
    [
        "mean radius",
        "mean texture",
        "mean area",
        "mean smoothness"
    ]
].boxplot()

plt.title(
    "Feature Distribution Before Scaling"
)

plt.ylabel(
    "Original Feature Values"
)

plt.xticks(
    rotation=15
)

plt.tight_layout()

plt.show()


# ============================================================
# 12. VISUALIZE STANDARDIZED FEATURES
# ============================================================

standard_df = pd.DataFrame(
    X_train_standard,
    columns=X_train.columns
)

plt.figure(
    figsize=(6, 4)
)

standard_df[
    [
        "mean radius",
        "mean texture",
        "mean area",
        "mean smoothness"
    ]
].boxplot()

plt.title(
    "Feature Distribution After Standardization"
)

plt.ylabel(
    "Standardized Values"
)

plt.xticks(
    rotation=15
)

plt.tight_layout()

plt.show()


# ============================================================
# 13. CONFUSION MATRIX - STANDARDIZED MODEL
# ============================================================

print("\n" + "=" * 60)
print("CONFUSION MATRIX - STANDARDIZED KNN")
print("=" * 60)

cm = confusion_matrix(
    y_test,
    pred_standard
)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=data.target_names
)

disp.plot()

plt.title(
    "KNN with StandardScaler - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        pred_standard,
        target_names=data.target_names
    )
)


# ============================================================
# 15. CHECK STANDARDIZED STATISTICS
# ============================================================

print("\n" + "=" * 60)
print("STANDARDIZED DATA STATISTICS")
print("=" * 60)

print(
    standard_df[
        [
            "mean radius",
            "mean texture",
            "mean area",
            "mean smoothness"
        ]
    ].describe().round(3)
)


# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(
    f"Accuracy Without Scaling : "
    f"{accuracy_unscaled:.4f}"
)

print(
    f"Accuracy StandardScaler  : "
    f"{accuracy_standard:.4f}"
)

print(
    f"Accuracy MinMaxScaler    : "
    f"{accuracy_minmax:.4f}"
)

best_method = comparison.loc[
    comparison["Accuracy"].idxmax(),
    "Method"
]

best_accuracy = comparison["Accuracy"].max()

print(
    f"\nBest Method: {best_method}"
)

print(
    f"Best Accuracy: {best_accuracy:.4f}"
)

print(
    "\nDay 17 Feature Scaling Complete! 🚀"
)

print("=" * 60)