# -*- coding: utf-8 -*-
"""day23_cross_validation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkczwK-s3KAxWbGsU_OXyqhqMy4cC-Jx
"""

# ============================================================
# DAY 23 — CROSS VALIDATION
# Model Performance Evaluation using K-Fold Cross Validation
# ============================================================

import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


# ============================================================
# 1. Load Dataset
# ============================================================

data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="target")

print("=" * 60)
print("DAY 23 — CROSS VALIDATION")
print("=" * 60)

print("\nDataset Shape:")
print(X.shape)

print("\nTarget Classes:")
print(data.target_names)


# ============================================================
# 2. Train-Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", X_train.shape[0])
print("Testing Samples :", X_test.shape[0])


# ============================================================
# 3. Define Models
# ============================================================

models = {

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=5000))
    ]),

    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier(n_neighbors=5))
    ]),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
}


# ============================================================
# 4. Define 5-Fold Stratified Cross Validation
# ============================================================

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# ============================================================
# 5. Perform Cross Validation
# ============================================================

results = []

print("\n" + "=" * 60)
print("5-FOLD CROSS VALIDATION RESULTS")
print("=" * 60)

for model_name, model in models.items():

    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1
    )

    mean_score = scores.mean()
    std_score = scores.std()

    results.append({
        "Model": model_name,
        "Mean Accuracy": mean_score,
        "Std Deviation": std_score
    })

    print(f"\n{model_name}")
    print("-" * 40)

    print("Fold Scores:")
    print(scores)

    print(f"Mean Accuracy : {mean_score:.4f}")
    print(f"Std Deviation : {std_score:.4f}")


# ============================================================
# 6. Create Results DataFrame
# ============================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Mean Accuracy",
    ascending=False
)

print("\n" + "=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

print(results_df.to_string(index=False))


# ============================================================
# 7. Identify Best Model
# ============================================================

best_model_name = results_df.iloc[0]["Model"]
best_score = results_df.iloc[0]["Mean Accuracy"]

print("\n" + "=" * 60)
print("BEST MODEL")
print("=" * 60)

print("Model:", best_model_name)
print(f"Mean CV Accuracy: {best_score:.4f}")


# ============================================================
# 8. Train Best Model on Training Data
# ============================================================

best_model = models[best_model_name]

best_model.fit(X_train, y_train)

test_accuracy = best_model.score(X_test, y_test)

print("\n" + "=" * 60)
print("FINAL TEST PERFORMANCE")
print("=" * 60)

print(f"Test Accuracy: {test_accuracy:.4f}")


# ============================================================
# 9. Save Results
# ============================================================

results_df.to_csv(
    "Day23_Cross_Validation_Results.csv",
    index=False
)

print("\nResults saved to:")
print("Day23_Cross_Validation_Results.csv")


# ============================================================
# 10. Final Summary
# ============================================================

print("\n" + "=" * 60)
print("DAY 23 SUMMARY")
print("=" * 60)

print("""
1. Applied 5-Fold Stratified Cross Validation.
2. Evaluated Logistic Regression, KNN and Random Forest.
3. Calculated mean accuracy and standard deviation.
4. Compared model performance and stability.
5. Selected the model with the highest mean CV accuracy.
6. Evaluated the selected model on unseen test data.
""")

print("Day 23/30 Completed Successfully! ✅")