# -*- coding: utf-8 -*-
"""DAY5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y25DLHSXr3RNX9IqRUcpe7izJkQQpSj6
"""

# ==========================================
# 3-6. Data Visualization - 2 x 2 Layout
# ==========================================

# Prepare data
product_sales = df.groupby("Product")["Sales"].sum()

monthly_sales = df.groupby(
    df["Date"].dt.to_period("M")
)["Sales"].sum()

monthly_sales.index = monthly_sales.index.astype(str)


# Create 2 x 2 figure
fig, axes = plt.subplots(2, 2, figsize=(14, 10))


# ==========================================
# 1. Bar Chart
# ==========================================

product_sales.plot(
    kind="bar",
    ax=axes[0, 0]
)

axes[0, 0].set_title("Total Sales by Product")
axes[0, 0].set_xlabel("Product")
axes[0, 0].set_ylabel("Sales")
axes[0, 0].tick_params(axis="x", rotation=45)


# ==========================================
# 2. Line Chart
# ==========================================

axes[0, 1].plot(
    monthly_sales.index,
    monthly_sales.values,
    marker="o"
)

axes[0, 1].set_title("Monthly Sales Trend")
axes[0, 1].set_xlabel("Month")
axes[0, 1].set_ylabel("Sales")
axes[0, 1].tick_params(axis="x", rotation=45)


# ==========================================
# 3. Scatter Plot
# ==========================================

axes[1, 0].scatter(
    df["Quantity"],
    df["Sales"]
)

axes[1, 0].set_title("Quantity vs Sales")
axes[1, 0].set_xlabel("Quantity")
axes[1, 0].set_ylabel("Sales")


# ==========================================
# 4. Histogram
# ==========================================

axes[1, 1].hist(
    df["Sales"],
    bins=6
)

axes[1, 1].set_title("Sales Distribution")
axes[1, 1].set_xlabel("Sales")
axes[1, 1].set_ylabel("Frequency")


# Adjust Layout
plt.suptitle(
    "Sales Data Visualization Dashboard",
    fontsize=16
)

plt.tight_layout()

plt.show()