# -*- coding: utf-8 -*-
"""day25_ensemble_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PCjFXIkG-35NWvWEijPOIKi7Vfhzd6f
"""

# ============================================================
# DAY 25 — ENSEMBLE LEARNING
# Bank Customer Subscription Prediction
# ============================================================

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    VotingClassifier
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    roc_curve
)


# ============================================================
# 1. Configuration
# ============================================================

DATA_PATH = Path("bank-full.csv")

RANDOM_STATE = 42


# ============================================================
# 2. Load Dataset
# ============================================================

print("=" * 70)
print("DAY 25 — ENSEMBLE LEARNING")
print("Bank Customer Subscription Prediction")
print("=" * 70)

if not DATA_PATH.exists():
    raise FileNotFoundError(
        "\nDataset not found!\n"
        "Please place 'bank-full.csv' in the same folder as this Python file."
    )

df = pd.read_csv(DATA_PATH, sep=";")

print("\nDataset loaded successfully!")

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())

print("\nDataset Information:")
print(df.info())


# ============================================================
# 3. Data Quality Check
# ============================================================

print("\n" + "=" * 70)
print("DATA QUALITY CHECK")
print("=" * 70)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nTarget Distribution:")
print(df["y"].value_counts())

print("\nTarget Percentage:")
print(
    df["y"].value_counts(normalize=True).mul(100).round(2)
)


# ============================================================
# 4. Remove Duplicate Rows
# ============================================================

before_duplicates = len(df)

df = df.drop_duplicates().reset_index(drop=True)

after_duplicates = len(df)

print("\nDuplicates Removed:", before_duplicates - after_duplicates)
print("New Dataset Shape:", df.shape)


# ============================================================
# 5. Target Encoding
# ============================================================
# Target:
# yes = customer subscribed
# no  = customer did not subscribe
df["y"] = df["y"].map({
    "no": 0,
    "yes": 1
})
print("\nEncoded Target Distribution:")
print(df["y"].value_counts())
# ============================================================
# 6. Feature Engineering
# ============================================================
print("\n" + "=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)
# Age groups
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 45, 55, 100],
    labels=[
        "Young",
        "Adult",
        "Mid_Age",
        "Senior",
        "Elder"
    ]
)
# Balance categories
df["balance_category"] = pd.cut(
    df["balance"],
    bins=[-np.inf, 0, 1000, 5000, np.inf],
    labels=[
        "Negative",
        "Low",
        "Medium",
        "High"
    ]
)

# Campaign intensity
df["campaign_intensity"] = pd.cut(
    df["campaign"],
    bins=[0, 1, 3, 5, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very_High"
    ]
)

print("\nNew Features Created:")
print("- age_group")
print("- balance_category")
print("- campaign_intensity")
# ============================================================
# 7. Separate Features and Target
# ============================================================
X = df.drop("y", axis=1)
y = df["y"]
# ============================================================
# 8. Identify Feature Types
# ============================================================

numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("\nNumerical Features:")
print(numeric_features)

print("\nCategorical Features:")
print(categorical_features)


# ============================================================
# 9. Train-Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y
)

print("\n" + "=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)

print("Training Samples:", X_train.shape[0])
print("Testing Samples :", X_test.shape[0])


# ============================================================
# 10. Preprocessing Pipeline
# ============================================================

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            StandardScaler(),
            numeric_features
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_features
        )
    ]
)
# ============================================================
# 11. Define Individual Models
logistic_regression = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=RANDOM_STATE
            )
        )
    ]
)
random_forest = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestClassifier(
                n_estimators=200,
                max_depth=15,
                min_samples_split=5,
                min_samples_leaf=2,
                class_weight="balanced",
                random_state=RANDOM_STATE,
                n_jobs=-1
            )
        )
    ]
)
gradient_boosting = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            GradientBoostingClassifier(
                n_estimators=150,
                learning_rate=0.05,
                max_depth=3,
                random_state=RANDOM_STATE
            )
        )
    ]
)
# 12. Create Voting Ensemble
voting_ensemble = VotingClassifier(
    estimators=[
        ("logistic_regression", logistic_regression),
        ("random_forest", random_forest),
        ("gradient_boosting", gradient_boosting)
    ],
    voting="soft"
)
# ============================================================
# 13. Store Models
# ============================================================
models = {
    "Logistic Regression": logistic_regression,
    "Random Forest": random_forest,
    "Gradient Boosting": gradient_boosting,
    "Voting Ensemble": voting_ensemble
}
# ============================================================
# 14. Train and Evaluate Models
# ============================================================
print("MODEL TRAINING & EVALUATION")
results = []

predictions = {}

for model_name, model in models.items():

    print(f"\nTraining: {model_name}")

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    y_prob = model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(
        y_test,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred,
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_test,
        y_prob
    )

    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1,
        "ROC-AUC": roc_auc
    })

    predictions[model_name] = {
        "prediction": y_pred,
        "probability": y_prob
    }
    print(f"Accuracy  : {accuracy:.4f}")
    print(f"Precision : {precision:.4f}")
    print(f"Recall    : {recall:.4f}")
    print(f"F1-Score  : {f1:.4f}")
    print(f"ROC-AUC   : {roc_auc:.4f}")
# ============================================================
# 15. Model Comparison
# ============================================================
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    by="ROC-AUC",
    ascending=False
).reset_index(drop=True)
print("MODEL COMPARISON")
print("=" * 70)
print(
    results_df.to_string(
        index=False
    )
)
# ============================================================
# 16. Select Best Model
# ============================================================

best_model_name = results_df.iloc[0]["Model"]

print("\n" + "=" * 70)
print("BEST MODEL")
print("=" * 70)

print("Best Model:", best_model_name)
print(
    f"Best ROC-AUC: "
    f"{results_df.iloc[0]['ROC-AUC']:.4f}"
)


# ============================================================
# 17. Cross Validation
# ============================================================

print("\n" + "=" * 70)
print("5-FOLD CROSS VALIDATION")
print("=" * 70)

cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=RANDOM_STATE
)

cv_models = {
    "Random Forest": random_forest,
    "Gradient Boosting": gradient_boosting
}

cv_results = []

for model_name, model in cv_models.items():

    print(f"\nRunning CV for: {model_name}")

    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc",
        n_jobs=-1
    )

    cv_results.append({
        "Model": model_name,
        "Mean CV ROC-AUC": scores.mean(),
        "Std CV ROC-AUC": scores.std()
    })

    print("Fold Scores:", scores)
    print(f"Mean ROC-AUC: {scores.mean():.4f}")
    print(f"Std Dev     : {scores.std():.4f}")


cv_results_df = pd.DataFrame(cv_results)

print("\nCross-Validation Summary:")
print(cv_results_df.to_string(index=False))

# ============================================================
# 18. Confusion Matrix — Best Model
# ============================================================

best_predictions = predictions[best_model_name]["prediction"]

cm = confusion_matrix(
    y_test,
    best_predictions
)

print("\n" + "=" * 70)
print("BEST MODEL — CONFUSION MATRIX")
print("=" * 70)

print(cm)

print("\nTrue Negative :", cm[0, 0])
print("False Positive:", cm[0, 1])
print("False Negative:", cm[1, 0])
print("True Positive :", cm[1, 1])


ConfusionMatrixDisplay.from_predictions(
    y_test,
    best_predictions,
    display_labels=["No", "Yes"]
)

plt.title(
    f"{best_model_name} - Confusion Matrix"
)

plt.tight_layout()
plt.show()


# ============================================================
# 19. Classification Report
# ============================================================

print("\n" + "=" * 70)
print("CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y_test,
        best_predictions,
        target_names=["No Subscription", "Subscription"],
        zero_division=0
    )
)


# ============================================================
# 20. ROC Curve Comparison
# ============================================================

plt.figure(figsize=(6, 4))

for model_name, prediction_data in predictions.items():

    y_prob = prediction_data["probability"]

    fpr, tpr, _ = roc_curve(
        y_test,
        y_prob
    )

    auc_score = roc_auc_score(
        y_test,
        y_prob
    )

    plt.plot(
        fpr,
        tpr,
        label=f"{model_name} (AUC={auc_score:.3f})"
    )


plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Random Classifier"
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title(
    "ROC Curve Comparison — Ensemble Learning"
)

plt.legend()

plt.tight_layout()
plt.show()


# ============================================================
# 21. Feature Importance — Random Forest
# ============================================================

rf_model = random_forest.named_steps["model"]

rf_preprocessor = random_forest.named_steps[
    "preprocessor"
]

feature_names = (
    rf_preprocessor
    .get_feature_names_out()
)

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n" + "=" * 70)
print("TOP 15 IMPORTANT FEATURES — RANDOM FOREST")
print("=" * 70)

print(
    importance_df.head(15).to_string(
        index=False
    )
)


# ============================================================
# 22. Visualize Feature Importance
# ============================================================

top_features = importance_df.head(15)

plt.figure(figsize=(7, 5))

plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

plt.xlabel("Importance")
plt.ylabel("Feature")

plt.title(
    "Top 15 Random Forest Feature Importances"
)

plt.tight_layout()
plt.show()


# ============================================================
# 23. Business Insight — Subscription Rate
# ============================================================

subscription_rate = df["y"].mean() * 100

print("\n" + "=" * 70)
print("BUSINESS INSIGHT")
print("=" * 70)

print(
    f"Overall subscription rate: "
    f"{subscription_rate:.2f}%"
)

print("""
Business Interpretation:

The objective of this model is to identify customers
who are more likely to subscribe to a bank term deposit.

An ensemble approach combines predictions from multiple
models and can provide a more robust prediction than
depending on a single algorithm.

The predictions can potentially help marketing teams
prioritize customers who are more likely to respond
positively to campaigns.
""")


# ============================================================
# 24. Save Model Results
# ============================================================

results_df.to_csv(
    "Day25_Ensemble_Model_Results.csv",
    index=False
)

cv_results_df.to_csv(
    "Day25_Cross_Validation_Results.csv",
    index=False
)

importance_df.to_csv(
    "Day25_RandomForest_Feature_Importance.csv",
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print("✓ Day25_Ensemble_Model_Results.csv")
print("✓ Day25_Cross_Validation_Results.csv")
print("✓ Day25_RandomForest_Feature_Importance.csv")


# ============================================================
# 25. Final Summary
# ============================================================

print("\n" + "=" * 70)
print("DAY 25 FINAL SUMMARY")
print("=" * 70)

print("""
✓ Loaded and explored a real-world banking dataset
✓ Performed data quality checks
✓ Removed duplicate records
✓ Created business-oriented features
✓ Applied numerical scaling
✓ Applied categorical encoding
✓ Built Logistic Regression
✓ Built Random Forest
✓ Built Gradient Boosting
✓ Built Soft Voting Ensemble
✓ Compared multiple evaluation metrics
✓ Applied 5-Fold Cross Validation
✓ Analyzed Confusion Matrix
✓ Compared ROC-AUC
✓ Analyzed Feature Importance
✓ Generated Business Insights
✓ Exported model results

Day 25/30 Completed Successfully! 🚀
""")