# -*- coding: utf-8 -*-
"""day15_feature_engineering.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgj9uZbfQNvTgO06N0Gssr8zo--MOTH-
"""

# ============================================================
# DAY 15 - FEATURE ENGINEERING
# Titanic Dataset
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

print("=" * 60)
print("DAY 15 - FEATURE ENGINEERING")
print("=" * 60)

df = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
)

print("\nDataset Shape:")
print(df.shape)

print("\nOriginal Columns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 2. CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 60)
print("MISSING VALUES")
print("=" * 60)

print(
    df.isnull().sum()
)


# ============================================================
# 3. FEATURE ENGINEERING
# ============================================================

print("\n" + "=" * 60)
print("CREATING NEW FEATURES")
print("=" * 60)


# ------------------------------------------------------------
# Feature 1: Family Size
# ------------------------------------------------------------

df["FamilySize"] = (
    df["sibsp"] +
    df["parch"] +1
)
# ------------------------------------------------------------
# Feature 2: Is Alone
# ------------------------------------------------------------

df["IsAlone"] = (
    df["FamilySize"] == 1
).astype(int)
# ------------------------------------------------------------
# Feature 3: Fare Per Person
# ------------------------------------------------------------

df["FarePerPerson"] = (
    df["fare"] /
    df["FamilySize"]
)
# ------------------------------------------------------------
# Feature 4: Title
# ------------------------------------------------------------

df["Title"] = (
    df["who"]
    .astype(str)
    .str.title()
)


# ------------------------------------------------------------
# Feature 5: Age Group
# ------------------------------------------------------------
df["AgeGroup"] = pd.cut(
    df["age"],
    bins=[
        0,
        12,
        18,
        35,
        60,
        100
    ],
    labels=[
        "Child",
        "Teen",
        "Young Adult",
        "Adult",
        "Senior"
    ]
)
# ============================================================
# 4. DISPLAY ENGINEERED FEATURES
# ============================================================

print("\nNew Features:")

print(
    df[
        [
            "FamilySize",
            "IsAlone",
            "FarePerPerson",
            "Title",
            "AgeGroup"
        ]
    ].head(10)
)


# ============================================================
# 5. COMPARE BEFORE AND AFTER
# ============================================================

print("\nOriginal Number of Features:")

original_features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked",
    "class",
    "who",
    "adult_male",
    "deck",
    "embark_town",
    "alive",
    "alone"
]

print(
    len(original_features)
)

print("\nNumber of Engineered Features:")

engineered_features = [
    "FamilySize",
    "IsAlone",
    "FarePerPerson",
    "Title",
    "AgeGroup"
]

print(
    len(engineered_features)
)


# ============================================================
# 6. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "pclass",
    "sex",
    "age",
    "fare",
    "embarked",
    "FamilySize",
    "IsAlone",
    "FarePerPerson",
    "Title",
    "AgeGroup"
]

X = df[features]

y = df["survived"]


# ============================================================
# 7. IDENTIFY NUMERICAL & CATEGORICAL FEATURES
# ============================================================

numeric_features = [
    "pclass",
    "age",
    "fare",
    "FamilySize",
    "IsAlone",
    "FarePerPerson"
]

categorical_features = [
    "sex",
    "embarked",
    "Title",
    "AgeGroup"
]


# ============================================================
# 8. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples :", len(X_test))


# ============================================================
# 9. PREPROCESSING
# ============================================================

numeric_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])


categorical_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(
            handle_unknown="ignore"
        )
    )
])


preprocessor = ColumnTransformer([
    (
        "numeric",
        numeric_pipeline,
        numeric_features
    ),
    (
        "categorical",
        categorical_pipeline,
        categorical_features
    )
])


# ============================================================
# 10. LOGISTIC REGRESSION MODEL
# ============================================================

model = Pipeline([
    (
        "preprocessor",
        preprocessor
    ),
    (
        "classifier",
        LogisticRegression(
            max_iter=1000
        )
    )
])


# ============================================================
# 11. TRAIN MODEL
# ============================================================

print("\n" + "=" * 60)
print("TRAINING MODEL")
print("=" * 60)

model.fit(
    X_train,
    y_train
)


# ============================================================
# 12. PREDICTION
# ============================================================

y_pred = model.predict(
    X_test
)


# ============================================================
# 13. MODEL EVALUATION
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\nAccuracy:")

print(
    f"{accuracy:.4f}"
)


print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred
    )
)


# ============================================================
# 14. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")

print(cm)


disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Not Survived",
        "Survived"
    ]
)

disp.plot()

plt.title(
    "Feature Engineering - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 15. FEATURE ENGINEERING VISUALIZATION
# ============================================================

plt.figure(
    figsize=(6, 4)
)

df.groupby(
    "FamilySize"
)["survived"].mean().head(8).plot(
    kind="bar"
)

plt.xlabel(
    "Family Size"
)

plt.ylabel(
    "Survival Rate"
)

plt.title(
    "Survival Rate by Family Size"
)

plt.tight_layout()

plt.show()


# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(
    f"Dataset Shape       : {df.shape}"
)

print(
    f"Training Samples    : {len(X_train)}"
)

print(
    f"Testing Samples     : {len(X_test)}"
)

print(
    f"Model Accuracy      : {accuracy:.4f}"
)

print(
    "\nEngineered Features:"
)

for feature in engineered_features:
    print(
        f"- {feature}"
    )

print(
    "\nDay 15 Feature Engineering Complete!"
)

print("=" * 60)