# -*- coding: utf-8 -*-
"""Day8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6OWxu4oZODFkgWnxFSrHdsfHz_gojF2
"""

"""
Day 8 - Logistic Regression
30 Days of Machine Learning Challenge
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# ==========================================
# 1. Load Dataset
# ==========================================

df = pd.read_csv(
    "StudentPerformanceFactors.csv"
)

print("First 5 Records:")
print(df.head())


# ==========================================
# 2. Explore Dataset
# ==========================================

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())


# ==========================================
# 3. Create Classification Target
# ==========================================

df["Performance"] = (
    df["Exam_Score"] >= 75
).astype(int)

print("\nPerformance Distribution:")
print(df["Performance"].value_counts())


# ==========================================
# 4. Visualize Classes
# ==========================================

plt.figure(figsize=(6, 4))

sns.countplot(
    x="Performance",
    data=df
)

plt.title("Performance Class Distribution")
plt.xlabel("Performance (0 = Low, 1 = High)")
plt.ylabel("Number of Students")

plt.tight_layout()
plt.show()


# ==========================================
# 5. Select Features and Target
# ==========================================

features = [
    "Hours_Studied",
    "Attendance",
    "Previous_Scores",
    "Sleep_Hours",
    "Tutoring_Sessions"
]

X = df[features]

y = df["Performance"]


# ==========================================
# 6. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)


# ==========================================
# 7. Create Model
# ==========================================

model = LogisticRegression(
    max_iter=1000
)


# ==========================================
# 8. Train Model
# ==========================================

model.fit(
    X_train,
    y_train
)

print("\nModel Training Completed!")


# ==========================================
# 9. Predictions
# ==========================================

y_pred = model.predict(X_test)

print("\nFirst 20 Predictions:")
print(y_pred[:20])


# ==========================================
# 10. Evaluation Metrics
# ==========================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred
)

recall = recall_score(
    y_test,
    y_pred
)

f1 = f1_score(
    y_test,
    y_pred
)

print("\nModel Evaluation")
print("-------------------------")

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)


# ==========================================
# 11. Classification Report
# ==========================================

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred
    )
)


# ==========================================
# 12. Confusion Matrix
# ==========================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)


# ==========================================
# 13. Confusion Matrix Visualization
# ==========================================

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.tight_layout()
plt.show()


# ==========================================
# 14. Model Coefficients
# ==========================================

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

print("\nModel Coefficients:")
print(
    coefficients.sort_values(
        "Coefficient",
        ascending=False
    )
)


# ==========================================
# 15. New Student Prediction
# ==========================================

new_student = pd.DataFrame({
    "Hours_Studied": [6],
    "Attendance": [90],
    "Previous_Scores": [75],
    "Sleep_Hours": [7],
    "Tutoring_Sessions": [2]
})

prediction = model.predict(
    new_student
)

probability = model.predict_proba(
    new_student
)

if prediction[0] == 1:
    print("\nPredicted Performance: High")
else:
    print("\nPredicted Performance: Low")

print("Prediction Probability:")
print(probability)