# -*- coding: utf-8 -*-
"""Day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAvKqWQYHgkSzI82P-Zynl4iBhXYDLqz
"""

"""
Day 2 - Data Preprocessing
30 Days of Machine Learning Challenge
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


# ==========================================
# 1. Create Sample Dataset
# ==========================================

data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Amit", "Neha"],
    "Age": [22, 21, np.nan, 23, 22, 24],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Pune", "Mumbai"],
    "Marks": [85, 90, 78, np.nan, 85, 95]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)


# ==========================================
# 2. Explore Dataset
# ==========================================

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()


# ==========================================
# 3. Check Missing Values
# ==========================================

print("\nMissing Values:")
print(df.isnull().sum())


# ==========================================
# 4. Handle Missing Values
# ==========================================

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print("\nAfter Handling Missing Values:")
print(df)


# ==========================================
# 5. Check Duplicates
# ==========================================

print("\nNumber of Duplicate Records:")
print(df.duplicated().sum())


# ==========================================
# 6. Remove Duplicates
# ==========================================

df = df.drop_duplicates()

print("\nDataset After Removing Duplicates:")
print(df)


# ==========================================
# 7. Check Data Types
# ==========================================

print("\nData Types:")
print(df.dtypes)


# ==========================================
# 8. Encode Categorical Data
# ==========================================

df_encoded = pd.get_dummies(
    df,
    columns=["City"],
    dtype=int
)

print("\nEncoded Dataset:")
print(df_encoded)


# ==========================================
# 9. Separate Features and Target
# ==========================================

X = df_encoded.drop("Marks", axis=1)

y = df_encoded["Marks"]

print("\nFeatures:")
print(X)

print("\nTarget:")
print(y)


# ==========================================
# 10. Train-Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)