# -*- coding: utf-8 -*-
"""day16_feature_selection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWgj_8TfuYf5NdphUDpfv6dpuSYSVs80
"""

# ============================================================
# DAY 16 - FEATURE SELECTION
# Dataset: Titanic
# Model: Logistic Regression
# Technique: SelectKBest + ANOVA F-test
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

print("=" * 60)
print("DAY 16 - FEATURE SELECTION")
print("=" * 60)

df = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
)

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 2. FEATURE ENGINEERING
# ============================================================

df["FamilySize"] = (
    df["sibsp"] +
    df["parch"] +
    1
)

df["IsAlone"] = (
    df["FamilySize"] == 1
).astype(int)

df["FarePerPerson"] = (
    df["fare"] /
    df["FamilySize"]
)

df["Title"] = (
    df["who"]
    .astype(str)
    .str.title()
)

df["AgeGroup"] = pd.cut(
    df["age"],
    bins=[
        0,
        12,
        18,
        35,
        60,
        100
    ],
    labels=[
        "Child",
        "Teen",
        "Young Adult",
        "Adult",
        "Senior"
    ]
)


# ============================================================
# 3. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "pclass",
    "sex",
    "age",
    "fare",
    "embarked",
    "FamilySize",
    "IsAlone",
    "FarePerPerson",
    "Title",
    "AgeGroup"
]

X = df[features]

y = df["survived"]


# ============================================================
# 4. DEFINE FEATURE TYPES
# ============================================================

numeric_features = [
    "pclass",
    "age",
    "fare",
    "FamilySize",
    "IsAlone",
    "FarePerPerson"
]

categorical_features = [
    "sex",
    "embarked",
    "Title",
    "AgeGroup"
]


# ============================================================
# 5. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples :", len(X_test))


# ============================================================
# 6. PREPROCESSING
# ============================================================

numeric_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    ),
    (
        "scaler",
        StandardScaler()
    )
])

categorical_pipeline = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(
            handle_unknown="ignore"
        )
    )
])

preprocessor = ColumnTransformer([
    (
        "numeric",
        numeric_pipeline,
        numeric_features
    ),
    (
        "categorical",
        categorical_pipeline,
        categorical_features
    )
])


# ============================================================
# 7. BASELINE MODEL - ALL FEATURES
# ============================================================

print("\n" + "=" * 60)
print("BASELINE MODEL - ALL FEATURES")
print("=" * 60)

baseline_model = Pipeline([
    (
        "preprocessor",
        preprocessor
    ),
    (
        "classifier",
        LogisticRegression(
            max_iter=1000
        )
    )
])

baseline_model.fit(
    X_train,
    y_train
)

baseline_pred = baseline_model.predict(
    X_test
)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_pred
)

print(
    f"\nBaseline Accuracy: "
    f"{baseline_accuracy:.4f}"
)


# ============================================================
# 8. TRANSFORM DATA FOR FEATURE SELECTION
# ============================================================

print("\n" + "=" * 60)
print("FEATURE SELECTION")
print("=" * 60)

X_train_processed = preprocessor.fit_transform(
    X_train
)

X_test_processed = preprocessor.transform(
    X_test
)

feature_names = (
    preprocessor
    .get_feature_names_out()
)

print(
    "\nTotal Features After Encoding:",
    len(feature_names)
)
# 9. SELECT TOP K FEATURES
k = 10

selector = SelectKBest(
    score_func=f_classif,
    k=k
)

X_train_selected = selector.fit_transform(
    X_train_processed,
    y_train
)

X_test_selected = selector.transform(
    X_test_processed
)

selected_features = feature_names[
    selector.get_support()
]

print(
    f"\nTop {k} Selected Features:"
)

for feature in selected_features:
    print(
        "-",
        feature
    )


# ============================================================
# 10. FEATURE SCORES
# ============================================================

feature_scores = pd.DataFrame({
    "Feature": feature_names,
    "Score": selector.scores_
})

feature_scores = (
    feature_scores
    .sort_values(
        by="Score",
        ascending=False
    )
)

print(
    "\nTop Features by F-Score:"
)

print(
    feature_scores
    .head(10)
    .to_string(index=False)
)


# ============================================================
# 11. TRAIN MODEL USING SELECTED FEATURES
# ============================================================

selected_model = LogisticRegression(
    max_iter=1000
)

selected_model.fit(
    X_train_selected,
    y_train
)

selected_pred = selected_model.predict(
    X_test_selected
)

selected_accuracy = accuracy_score(
    y_test,
    selected_pred
)

print(
    f"\nSelected Features Accuracy: "
    f"{selected_accuracy:.4f}"
)


# ============================================================
# 12. COMPARE MODELS
# ============================================================

print("\n" + "=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

comparison = pd.DataFrame({
    "Model": [
        "All Features",
        "Selected Features"
    ],
    "Accuracy": [
        baseline_accuracy,
        selected_accuracy
    ]
})

print(
    comparison.to_string(
        index=False
    )
)

improvement = (
    selected_accuracy -
    baseline_accuracy
)

print(
    f"\nAccuracy Difference: "
    f"{improvement:.4f}"
)


# ============================================================
# 13. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT - SELECTED FEATURES")
print("=" * 60)

print(
    classification_report(
        y_test,
        selected_pred
    )
)


# ============================================================
# 14. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    selected_pred
)

print("\nConfusion Matrix:")

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Not Survived",
        "Survived"
    ]
)

disp.plot()

plt.title(
    "Feature Selection - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 15. TOP FEATURES VISUALIZATION
# ============================================================

top_features = (
    feature_scores
    .head(10)
    .sort_values(
        "Score"
    )
)

plt.figure(
    figsize=(5, 4)
)

plt.barh(
    top_features["Feature"],
    top_features["Score"]
)

plt.xlabel(
    "F-Score"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "Top 10 Features Selected by F-Score"
)

plt.tight_layout()

plt.show()


# ============================================================
# 16. MODEL COMPARISON VISUALIZATION
# ============================================================

plt.figure(
    figsize=(5, 4)
)

plt.bar(
    comparison["Model"],
    comparison["Accuracy"]
)

plt.ylim(
    0,
    1
)

plt.ylabel(
    "Accuracy"
)

plt.title(
    "All Features vs Selected Features"
)

plt.tight_layout()

plt.show()


# ============================================================
# 17. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)

print(
    f"Total Processed Features : "
    f"{len(feature_names)}"
)

print(
    f"Selected Features        : "
    f"{k}"
)

print(
    f"All Features Accuracy    : "
    f"{baseline_accuracy:.4f}"
)

print(
    f"Selected Features Accuracy: "
    f"{selected_accuracy:.4f}"
)

print(
    f"Accuracy Difference      : "
    f"{improvement:.4f}"
)

print(
    "\nSelected Features:"
)

for feature in selected_features:
    print(
        f"- {feature}"
    )

print(
    "\nDay 16 Feature Selection Complete!"
)

print("=" * 60)