# -*- coding: utf-8 -*-
"""Day12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiR_b1zcVMY68HBeMX05annN-PJuQs7O
"""

# ============================================================
# DAY 13 - MACHINE LEARNING MODEL COMPARISON
# 30 Days Machine Learning Challenge
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# ============================================================
# 1. LOAD DATASET
# ============================================================

df = pd.read_csv("StudentPerformanceFactors.csv")

print("=" * 70)
print("DAY 13 - MACHINE LEARNING MODEL COMPARISON")
print("=" * 70)

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())


# ============================================================
# 2. BASIC DATA CHECK
# ============================================================

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())


# ============================================================
# 3. REMOVE DUPLICATES
# ============================================================

df = df.drop_duplicates()

print("\nShape After Removing Duplicates:")
print(df.shape)


# ============================================================
# 4. CREATE PASS/FAIL TARGET
# ============================================================

# The original dataset does not contain Pass/Fail.
# We create it using the median Exam Score.

median_score = df["Exam_Score"].median()

df["Pass"] = (
    df["Exam_Score"] >= median_score
).astype(int)

print("\nMedian Exam Score:")
print(median_score)

print("\nPass/Fail Distribution:")
print(df["Pass"].value_counts())


# ============================================================
# 5. CHECK TARGET
# ============================================================

if df["Pass"].nunique() < 2:
    raise ValueError(
        "Target contains only one class. "
        "At least two classes are required."
    )


# ============================================================
# 6. SELECT FEATURES
# ============================================================

X = df[
    [
        "Hours_Studied",
        "Attendance",
        "Previous_Scores",
        "Sleep_Hours",
        "Tutoring_Sessions",
        "Physical_Activity"
    ]
]

y = df["Pass"]

print("\nFeatures:")
print(X.head())

print("\nTarget:")
print(y.head())


# ============================================================
# 7. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:")
print(X_train.shape)

print("\nTesting Data Shape:")
print(X_test.shape)


# ============================================================
# 8. CREATE MODELS
# ============================================================

decision_tree = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42
)

naive_bayes = GaussianNB()

random_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)


# ============================================================
# 9. TRAIN MODELS
# ============================================================

print("\nTraining Decision Tree...")
decision_tree.fit(X_train, y_train)

print("Training Naive Bayes...")
naive_bayes.fit(X_train, y_train)

print("Training Random Forest...")
random_forest.fit(X_train, y_train)

print("\nAll models trained successfully!")


# ============================================================
# 10. PREDICTIONS
# ============================================================

dt_pred = decision_tree.predict(X_test)

nb_pred = naive_bayes.predict(X_test)

rf_pred = random_forest.predict(X_test)


# ============================================================
# 11. MODEL COMPARISON
# ============================================================

models = {
    "Decision Tree": (decision_tree, dt_pred),
    "Naive Bayes": (naive_bayes, nb_pred),
    "Random Forest": (random_forest, rf_pred)
}

results = []

for name, (model, predictions) in models.items():

    results.append({
        "Model": name,

        "Training Accuracy": model.score(
            X_train,
            y_train
        ),

        "Testing Accuracy": accuracy_score(
            y_test,
            predictions
        ),

        "Precision": precision_score(
            y_test,
            predictions,
            zero_division=0
        ),

        "Recall": recall_score(
            y_test,
            predictions,
            zero_division=0
        ),

        "F1 Score": f1_score(
            y_test,
            predictions,
            zero_division=0
        )
    })


results_df = pd.DataFrame(results)


# ============================================================
# 12. DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 70)
print("MODEL COMPARISON RESULTS")
print("=" * 70)

print(
    results_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# ============================================================
# 13. BEST MODEL BY F1 SCORE
# ============================================================

best_model = results_df.loc[
    results_df["F1 Score"].idxmax()
]

print("\n" + "=" * 70)
print("BEST MODEL")
print("=" * 70)

print(
    f"\nBest Model: {best_model['Model']}"
)

print(
    f"F1 Score: {best_model['F1 Score']:.4f}"
)

print(
    f"Testing Accuracy: "
    f"{best_model['Testing Accuracy']:.4f}"
)


# ============================================================
# 14. CONFUSION MATRICES
# ============================================================

for name, (model, predictions) in models.items():

    cm = confusion_matrix(
        y_test,
        predictions,
        labels=[0, 1]
    )

    print("\n" + "-" * 50)
    print(f"{name} - Confusion Matrix")
    print("-" * 50)

    print(cm)


# ============================================================
# 15. CLASSIFICATION REPORTS
# ============================================================

for name, (model, predictions) in models.items():

    print("\n" + "=" * 70)
    print(f"{name} - Classification Report")
    print("=" * 70)

    print(
        classification_report(
            y_test,
            predictions,
            labels=[0, 1],
            target_names=["Fail", "Pass"],
            zero_division=0
        )
    )


# ============================================================
# 16. TESTING ACCURACY COMPARISON
# ============================================================

plt.figure(figsize=(6, 4))

plt.bar(
    results_df["Model"],
    results_df["Testing Accuracy"]
)

plt.title("Testing Accuracy Comparison")

plt.xlabel("Model")

plt.ylabel("Testing Accuracy")

plt.ylim(0, 1)

plt.xticks(rotation=0)

plt.tight_layout()

plt.show()


# ============================================================
# 17. ALL METRICS COMPARISON
# ============================================================

metrics = [
    "Testing Accuracy",
    "Precision",
    "Recall",
    "F1 Score"
]

results_df.set_index("Model")[metrics].plot(
    kind="bar",
    figsize=(8, 4)
)

plt.title(
    "Decision Tree vs Naive Bayes vs Random Forest"
)

plt.xlabel("Model")

plt.ylabel("Score")

plt.ylim(0, 1)

plt.xticks(rotation=0)

plt.legend()

plt.tight_layout()

plt.show()


# ============================================================
# 18. FEATURE IMPORTANCE
# ============================================================

print("\n" + "=" * 70)
print("FEATURE IMPORTANCE")
print("=" * 70)

# Decision Tree
dt_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": decision_tree.feature_importances_
})

dt_importance = dt_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nDecision Tree Feature Importance:")
print(dt_importance)


# Random Forest
rf_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": random_forest.feature_importances_
})

rf_importance = rf_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nRandom Forest Feature Importance:")
print(rf_importance)


# ============================================================
# 19. FINAL CONCLUSION
# ============================================================

print("\n" + "=" * 70)
print("DAY 13 COMPLETED")
print("=" * 70)

print("""
Models Compared:
1. Decision Tree
2. Naive Bayes
3. Random Forest

Evaluation Metrics:
- Training Accuracy
- Testing Accuracy
- Precision
- Recall
- F1 Score

The best model is selected based on the highest F1 Score.
""")